import fs from 'node:fs';
import path from 'node:path';

// Import existing translated namespaces
const { core } = await import('file:///D:/Project/deepseek-harness/packages/client/locale/src/locales/vi/core.ts');
const { dicts: convDicts } = await import('file:///D:/Project/deepseek-harness/packages/client/locale/src/locales/vi/conversation.ts');
const { dicts: panelDicts } = await import('file:///D:/Project/deepseek-harness/packages/client/locale/src/locales/vi/panels.ts');

// The remaining 41 namespaces translated to Vietnamese with accurate technical context
const additionalDicts = {
  'approval': {
    'waiting': 'Đang chờ phê duyệt',
    'detail.aria': 'Chi tiết phê duyệt',
    'escalation': 'Công cụ {toolName} yêu cầu nâng quyền thực thi (escalation)',
    'reject': 'Từ chối',
    'allowOnce': 'Cho phép một lần',
  },
  'command': {
    'section.add': 'Thêm',
    'section.commands': 'Lệnh',
    'label.goal': 'Mục tiêu (Goal)',
    'label.plan': 'Kế hoạch (Plan)',
    'label.feedback': 'Phản hồi (Feedback)',
    'label.compact': 'Nén ngữ cảnh (Compact)',
    'label.permission': 'Quyền hạn (Permission)',
    'label.export': 'Tải xuống nhật ký',
    'description.goal': 'Thiết lập hoặc xem mục tiêu cho tác vụ dài hạn',
    'description.plan': 'Bật hoặc tắt chế độ lập kế hoạch (/plan)',
    'description.feedback': 'Gửi phản hồi về phiên làm việc này',
    'description.compact': 'Nén nội dung lịch sử trò chuyện phía trên để giải phóng ngữ cảnh',
    'description.permission': 'Chuyển đổi preset quyền hạn (chế độ sandbox và chính sách phê duyệt)',
    'description.export': 'Xuất toàn bộ nhật ký phiên hiện tại thành tệp ZIP',
    'token.goal': 'mục tiêu',
    'token.plan': 'kế hoạch',
    'token.feedback': 'phản hồi',
    'token.compact': 'nén',
    'token.permission': 'quyền hạn',
    'token.export': 'xuất',
    'search.placeholder': 'Tìm kiếm lệnh…',
    'search.aria': 'Lọc tùy chọn lệnh',
    'status.loading': 'Đang tải tùy chọn…',
    'status.applying': 'Đang áp dụng…',
    'status.empty': 'Không có tùy chọn phù hợp',
    'overlay.aria': 'Tùy chọn /{command}',
    'listbox.aria': 'Kết quả phù hợp cho /{command}',
    'notice.attachmentsUnsupported': '/{command} không chấp nhận tệp đính kèm; vui lòng gỡ tệp trước',
  },
  'deliverables': {
    'presented.nativeUnavailable': 'Tệp này không có đường dẫn máy chủ khả dụng; hãy xem trước ở thanh bên',
    'presented.revealError': 'Không thể hiển thị trong trình quản lý tệp, vui lòng thử lại',
    'presented.directoryError': 'Không thể mở thư mục chứa tệp, vui lòng thử lại',
    'presented.directoryOpening': 'Đang mở thư mục chứa tệp…',
    'presented.directoryOpened': 'Đã yêu cầu mở thư mục chứa tệp',
    'presented.revealed': 'Đã yêu cầu hiển thị trong trình quản lý tệp',
    'presented.revealing': 'Đang hiển thị trong trình quản lý tệp…',
    'presented.unavailable': 'Máy chủ này không có môi trường màn hình để mở ứng dụng ngoài; tệp vẫn có thể xem trước ở thanh bên',
    'presented.retry': 'Thử lại',
    'presented.hostError': 'Không thể đọc thông tin màn hình của máy chủ',
    'presented.preview': 'Xem trước ở thanh bên',
    'presented.previewButton': 'Mở {name} ở thanh bên',
    'presented.previewCard': 'Xem trước {name} ở thanh bên',
    'presented.all': 'Tất cả {count} tệp',
    'presented.expandAria': 'Mở rộng tất cả {count} tệp bàn giao',
    'presented.collapse': 'Thu gọn',
    'presented.collapseAria': 'Thu gọn danh sách tệp bàn giao',
    'presented.opening': 'Đang mở…',
    'presented.opened': 'Đã gửi yêu cầu mở',
    'presented.error': 'Mở thất bại, nhấp để thử lại',
    'presented.file': 'Tệp bàn giao',
    'row.title': 'Bàn giao tệp',
    'row.running': 'Đang bàn giao',
    'row.ok': 'Đã bàn giao',
    'row.error': 'Bàn giao thất bại',
    'row.stopped': 'Đã ngắt',
    'row.inspect': 'Kiểm tra lượt gọi',
    'changes.title': 'Đã chỉnh sửa {count} tệp',
    'changes.added': '+{count}',
    'changes.deleted': '-{count}',
    'changes.binary': 'nhị phân',
    'changes.openReview': 'Xem xét thay đổi (Review) của lượt này ở thanh bên',
    'changes.all': 'Tất cả {count} tệp',
    'changes.expandAria': 'Mở rộng tất cả {count} tệp thay đổi',
    'changes.collapse': 'Thu gọn',
    'changes.collapseAria': 'Thu gọn danh sách tệp thay đổi',
    'changes.oversized': 'dung lượng quá lớn',
    'changes.viewDiff': 'Xem khác biệt (Diff) của {name}',
    'review.title': 'Xem xét thay đổi · Lượt {turn}',
    'review.selectFile': 'Chọn tệp cần xem xét',
    'review.split': 'Chuyển sang chế độ hai cột (Split view)',
    'review.unified': 'Chuyển sang chế độ một cột (Unified view)',
    'review.splitAria': 'Chế độ hai cột (Split view)',
    'review.wrap': 'Bật tự động xuống dòng (Word wrap)',
    'review.nowrap': 'Tắt tự động xuống dòng',
    'review.wrapAria': 'Tự động xuống dòng',
    'review.openFile': 'Mở toàn bộ tệp trong thanh bên',
    'review.openFileAria': 'Mở {name} trong thanh bên',
    'diff.loading': 'Đang nạp dữ liệu khác biệt (Diff)…',
    'diff.missing': 'Nội dung thay đổi của lượt này không còn khả dụng',
    'diff.error': 'Không thể đọc dữ liệu khác biệt',
    'diff.binary': 'Tệp nhị phân; không thể hiển thị khác biệt dạng văn bản',
    'diff.oversized': 'Tệp quá lớn; không thể hiển thị khác biệt',
    'diff.created': 'Tệp được tạo mới trong lượt này',
    'diff.deleted': 'Tệp bị xóa trong lượt này',
    'diff.unchanged': 'Nội dung hai bên giống nhau',
    'diff.coarse': 'Hết thời gian so sánh chi tiết từng dòng; hiển thị thay thế toàn bộ tệp',
    'diff.truncated': 'Chỉ hiển thị {count} dòng đầu tiên',
  },
  'feedback': {
    'action.like': 'Câu trả lời tốt',
    'action.likeActive': 'Hủy đánh giá',
    'action.dislike': 'Câu trả lời có vấn đề',
    'action.dislikeActive': 'Hủy đánh giá',
    'dialog.title': 'Gửi phản hồi',
    'dialog.categories': 'Phân loại phản hồi',
    'dialog.detail': 'Chi tiết phản hồi',
    'dialog.hint': 'Thêm chi tiết để giúp cải thiện trải nghiệm. Dữ liệu gửi sẽ bao gồm nhật ký của cuộc trò chuyện hiện tại.',
    'category.task-result': 'Kết quả tác vụ',
    'category.instruction-following': 'Hiểu và tuân thủ chỉ thị',
    'category.product-interaction': 'Tính năng và tương tác sản phẩm',
    'category.service-stability': 'Độ ổn định và tốc độ',
    'category.resource-cost': 'Mức sử dụng tài nguyên và chi phí',
    'category.security-privacy-permission': 'Bảo mật, quyền riêng tư và quyền hạn',
    'category.other': 'Khác',
    'toast.recorded': 'Cảm ơn phản hồi của bạn',
    'error.conflict': 'Phản hồi này đã được chỉnh sửa ở nơi khác; đang hiển thị trạng thái mới nhất',
    'error.load': 'Không thể tải trạng thái phản hồi',
    'error.generic': 'Lưu phản hồi thất bại',
    'error.noteTooLarge': 'Mô tả quá dài; vui lòng rút ngắn rồi gửi lại',
  },
  'goal': {
    'phase.active': 'Mục tiêu đang thực hiện',
    'phase.active.disarmed': 'Mục tiêu chưa kích hoạt',
    'phase.paused': 'Mục tiêu đã tạm dừng',
    'phase.blocked': 'Mục tiêu bị chặn (Blocked)',
    'objective.aria': 'Nội dung mục tiêu',
    'commandInput.aria': 'Nhập lệnh mục tiêu',
    'action.save': 'Lưu mục tiêu',
    'action.cancel': 'Hủy chỉnh sửa',
    'action.pause': 'Tạm dừng mục tiêu',
    'action.resume': 'Tiếp tục mục tiêu',
    'action.edit': 'Chỉnh sửa mục tiêu',
    'action.clear': 'Xóa mục tiêu',
  },
  'job': {
    'count.live.one': '{count} tác vụ nền đang chạy',
    'count.live.other': '{count} tác vụ nền đang chạy',
    'count.idle.one': '{count} tác vụ nền',
    'count.idle.other': '{count} tác vụ nền',
    'list.aria': 'Danh sách tác vụ nền',
    'section.live': 'Đang chạy',
    'section.settledCount': 'Đã kết thúc {count}',
    'section.clear': 'Xóa sạch',
    'row.expandAria': 'Mở rộng đầu ra thời gian thực của {label}',
    'row.collapseAria': 'Thu gọn đầu ra thời gian thực của {label}',
    'kill.stop': 'Dừng tác vụ {label}',
    'kill.confirm': 'Nhấp lần nữa để xác nhận dừng',
    'kill.confirmAction': 'Xác nhận dừng',
    'kill.failed': 'Dừng tác vụ thất bại',
    'status.running': 'đang chạy',
    'status.stopping': 'đang dừng',
    'status.completed': 'đã hoàn tất',
    'status.killed': 'đã hủy',
    'status.failed': 'thất bại',
    'duration.seconds': '{seconds}s',
    'duration.minutes': '{minutes}m {seconds}s',
    'duration.hours': '{hours}h {minutes}m',
    'duration.title.live': 'Đã chạy {duration}',
    'duration.title.done': 'Thời gian chạy {duration}',
    'output.gap': '… các dòng đầu ra trước đó đã được lược bớt …',
    'output.error': 'Luồng đầu ra thời gian thực bị gián đoạn: {error}',
    'terminal.signal': 'tín hiệu {signal}',
    'terminal.exitCode': 'mã thoát (exit code) {code}',
    'terminal.noExitCode': 'không có mã thoát',
    'terminal.running': 'đang chạy',
    'terminal.failed': 'thất bại',
    'terminal.done': 'hoàn tất',
    'terminal.copy': 'Sao chép',
    'terminal.copied': 'Đã sao chép',
    'terminal.noOutput': '(không có đầu ra)',
    'terminal.collapse': 'Thu gọn',
    'terminal.collapseAria': 'Thu gọn đầu ra',
    'terminal.expand': 'Mở rộng thêm {n} dòng',
    'terminal.expandAria': 'Mở rộng {n} dòng đầu ra bị thu gọn',
  },
  'model': {
    'command.label': 'Mô hình',
    'command.description': 'Chọn mô hình AI cho phiên hội thoại này',
    'option.loadError': 'Tải danh mục mô hình thất bại: {message}',
    'option.deepseekV4Flash.description': 'Nhanh, hiệu quả và tối ưu chi phí; phù hợp cho các tác vụ trọng tâm, thông thường hoặc song song.',
    'option.deepseekV4Pro.description': 'Khả năng lập trình tự động (agentic coding), kiến thức và suy luận phức tạp vượt trội; phù hợp cho tác vụ khó hoặc ưu tiên chất lượng cao.',
    'trigger.fallback': 'Chọn mô hình',
    'trigger.loading': 'Đang tải danh sách mô hình…',
    'trigger.selectAria': 'Chọn mô hình',
    'trigger.aria': 'Chọn mô hình, hiện tại {model}',
    'trigger.ariaEffort': 'Chọn mô hình, hiện tại {model}, mức độ suy luận {effort}',
    'menu.aria': 'Mô hình và mức độ suy luận (Reasoning effort)',
    'menu.model': 'Mô hình',
    'menu.effort': 'Mức độ suy luận',
    'effort.providerDefault': 'Mặc định nhà cung cấp',
    'status.loading': 'Đang làm mới danh mục mô hình…',
    'error.action': 'Thao tác mô hình thất bại: {message}',
    'error.sessionInUse': 'Phiên làm việc này đang được sử dụng bởi một tiến trình DSH khác (như dsh web hoặc desktop). Hãy thoát các phiên bản DSH khác rồi thử lại.',
    'action.reload': 'Tải lại',
    'warning.groupLoad': 'Tải nhóm {name} thất bại: {message}',
    'empty.models': 'Không có mô hình nào khả dụng.',
    'blocked.composer': 'Mô hình hiện tại không khả dụng — vui lòng chọn một mô hình để tiếp tục',
    'empty.efforts': 'Mô hình này không hỗ trợ tùy chỉnh mức độ suy luận.',
  },
  'open-in-app': {
    'open.title': 'Mở bằng {app}',
    'path.appDefault': '{app} (mặc định)',
    'path.appsError': 'Không thể lấy danh sách ứng dụng',
    'path.open': 'Mở',
    'path.more': 'Thêm tùy chọn mở',
    'path.reveal': 'Hiển thị vị trí tệp',
    'path.openError': 'Mở thất bại, vui lòng thử lại',
    'path.revealError': 'Không thể hiển thị vị trí tệp, vui lòng thử lại',
    'app.cursor': 'Cursor',
    'app.vscode': 'VS Code',
    'app.vscodeinsiders': 'VS Code Insiders',
    'app.windsurf': 'Windsurf',
    'app.zed': 'Zed',
    'app.sublimetext': 'Sublime Text',
    'app.xcode': 'Xcode',
    'app.androidstudio': 'Android Studio',
    'app.intellij': 'IntelliJ IDEA',
    'app.pycharm': 'PyCharm',
    'app.webstorm': 'WebStorm',
    'app.phpstorm': 'PhpStorm',
    'app.goland': 'GoLand',
    'app.rider': 'Rider',
    'app.rustrover': 'RustRover',
    'app.fork': 'Fork',
    'app.sourcetree': 'Sourcetree',
    'app.github': 'GitHub Desktop',
    'app.tower': 'Tower',
    'app.gitkraken': 'GitKraken',
    'app.smartgit': 'SmartGit',
    'app.sublimemerge': 'Sublime Merge',
    'app.ghostty': 'Ghostty',
    'app.warp': 'Warp',
    'app.iterm': 'iTerm2',
    'app.kitty': 'kitty',
    'app.windowsterminal': 'Windows Terminal',
    'app.gitbash': 'Git Bash',
    'app.gnometerminal': 'GNOME Terminal',
    'app.konsole': 'Konsole',
    'app.finder': 'Finder',
    'app.explorer': 'File Explorer',
    'app.filemanager': 'Trình quản lý tệp',
    'app.terminal': 'Terminal',
  },
  'permission.access': {
    'mode': 'Chế độ truy cập, hiện tại: {name}',
    'close': 'Đóng',
    'preset.readOnly': 'Chỉ xem (Read Only)',
    'preset.workspaceWrite': 'Ghi trong Workspace (Workspace Write)',
    'preset.fullAccess': 'Toàn quyền (Full Access)',
    'confirm.title': 'Xác nhận bật Toàn quyền (Full Access)?',
    'confirm.description': 'Khi kích hoạt Full Access, agent sẽ giảm thiểu các bước xin xác nhận và có thể trực tiếp thực thi nhiều hành động hơn, bao gồm thao tác nhạy cảm, thay đổi tệp hoặc chạy lệnh hệ thống bên ngoài. Chỉ khuyến nghị khi bạn hoàn toàn tin cậy tác vụ hiện tại.',
    'confirm.acknowledge': 'Tôi hiểu rõ rủi ro và muốn tiếp tục',
    'confirm.cancel': 'Hủy',
    'confirm.enable': 'Bật Toàn quyền',
    'auto.label': 'Auto review',
    'auto.badge': 'EXP',
    'auto.description': 'Chạy không có sandbox; mỗi lượt gọi công cụ nguyên bản và PTC được kiểm duyệt thử nghiệm trước bởi cùng một mô hình.',
    'auto.confirm.title': 'Xác nhận bật Auto review (Thử nghiệm)?',
    'auto.confirm.description': 'Auto review không kích hoạt sandbox. Trước mỗi lệnh gọi công cụ nguyên bản hoặc PTC nội bộ, mô hình hiện tại sẽ tự động kiểm duyệt đánh giá. Tính năng này đang trong giai đoạn thử nghiệm và sẽ tiêu tốn thêm token.',
    'auto.confirm.acknowledge': 'Tôi hiểu các rủi ro này và muốn tiếp tục',
    'auto.confirm.enable': 'Bật Auto review',
  },
  'plan': {
    'chip.label': 'Kế hoạch',
    'preview.title': 'Kế hoạch',
    'preview.document': 'Kế hoạch · Markdown',
    'preview.action': 'Mở',
    'preview.open': 'Mở kế hoạch ở thanh bên',
    'preview.full': 'Xem toàn văn kế hoạch',
    'preview.openNamed': 'Mở kế hoạch: {title}',
    'preview.loading': 'Đang đọc kế hoạch…',
    'preview.failed': 'Không thể tải kế hoạch',
    'preview.invalidAddress': 'Địa chỉ kế hoạch không hợp lệ',
    'preview.historyUnavailable': 'Không thể đọc lịch sử phiên',
    'preview.notFound': 'Không tìm thấy bản kế hoạch này',
    'preview.unavailable': 'Bản xem trước kế hoạch không khả dụng',
    'preview.expired': 'Bản xem trước tạm thời đã hết hạn. Hãy mở lại từ thẻ phê duyệt đang chờ.',
    'chip.on.aria': 'Chế độ kế hoạch đang bật; nhấn để tắt',
    'chip.on.title': 'Chế độ kế hoạch đang bật — nhấp để tắt (/plan off)',
    'chip.off.aria': 'Chế độ kế hoạch đang tắt; nhấn để bật',
    'chip.off.title': 'Chế độ kế hoạch đang tắt — nhấp để bật (/plan)',
    'chip.exitFailed': 'Thoát chế độ kế hoạch thất bại',
  },
  'question': {
    'error.incomplete': 'Vui lòng hoàn thành câu hỏi này trước.',
    'error.unanswered': 'Vui lòng chọn một tùy chọn hoặc nhập câu trả lời tùy chỉnh.',
    'nav.prev': 'Câu trước',
    'nav.next': 'Câu tiếp',
    'nav.minimize': 'Thu gọn thẻ câu hỏi',
    'nav.maximize': 'Mở rộng thẻ câu hỏi',
    'nav.cancel': 'Bỏ qua toàn bộ câu hỏi',
    'option.recommended': 'Khuyên dùng',
    'custom.placeholder': 'Nhập câu trả lời của bạn',
    'action.skip': 'Bỏ qua',
    'action.next': 'Tiếp tục',
    'plan.header': 'Duyệt kế hoạch thực thi',
    'plan.approve': 'Đồng ý thực hiện',
    'plan.decline': 'Từ chối',
    'plan.discuss': 'Yêu cầu điều chỉnh',
  },
  'reference': {
    'section.files': 'Tệp & thư mục',
    'section.subagents': 'Subagent',
    'section.sessions': 'Phiên hội thoại',
    'candidate.noCwd': '(không có thư mục làm việc)',
    'crumb.root': 'Workspace',
    'time.now': 'vừa xong',
    'time.minutes': '{n}m',
    'time.hours': '{n}h',
    'time.days': '{n}d',
    'time.months': '{n}mo',
    'time.years': '{n}y',
  },
  'schedule.catalog': {
    'trigger.one': '{count} lịch hẹn',
    'trigger.other': '{count} lịch hẹn',
    'list.aria': 'Danh sách lịch hẹn đang hoạt động',
    'status.scheduled': 'Đã lên lịch',
    'status.overdue': 'Quá hạn',
    'frequency.once': 'Một lần',
    'frequency.every': 'Mỗi {value} {unit}',
    'unit.day.one': 'ngày',
    'unit.day.other': 'ngày',
    'unit.hour.one': 'giờ',
    'unit.hour.other': 'giờ',
    'unit.minute.one': 'phút',
    'unit.minute.other': 'phút',
    'unit.second.one': 'giây',
    'unit.second.other': 'giây',
    'relative.now': 'Đến hạn ngay bây giờ',
    'relative.future': 'trong {value} {unit}',
    'relative.overdue': 'đã quá hạn {value} {unit}',
  },
  'skill': {
    'row.title': 'Kỹ năng (Skill)',
    'row.running': 'Đang nạp skill…',
    'row.failed': 'Nạp skill thất bại',
    'row.stopped': 'Đã dừng nạp skill',
    'row.instructions': 'Hướng dẫn chi tiết',
    'row.inspect': 'Kiểm tra',
    'menu.userOnly': 'chỉ người dùng',
  },
  'slash.menu': {
    'command': 'Lệnh (/command)',
    'skill': 'Kỹ năng (Skill)',
    'subagent': 'Subagent',
    'loading': 'Đang tải gợi ý…',
    'drill.aria': 'Duyệt thư mục',
    'drill.hint': 'Duyệt thư mục con',
    'drill.key': 'Tab',
    'crumbs.aria': 'Thanh điều hướng thư mục',
    'suggestions.aria': 'Gợi ý kích hoạt',
  },
  'subagent': {
    'duration.seconds': '{seconds}s',
    'duration.minutes': '{minutes}m {seconds}s',
    'duration.hours': '{hours}h {minutes}m {seconds}s',
    'duration.days': '{days}d',
    'duration.daysHours': '{days}d {hours}h',
    'duration.months': '~{months}mo',
    'duration.monthsDays': '~{months}mo {days}d',
    'duration.years': '~{years}y',
    'duration.yearsMonths': '~{years}y {months}mo',
    'duration.exactDays': '{days} ngày {hours} giờ {minutes} phút {seconds} giây',
    'duration.exactTitle': 'Tổng thời gian hoạt động thực: {duration}',
    'tokens.thousand': '{value}K',
    'tokens.million': '{value}M',
    'tokens.total': '{value} tok',
    'loading.label': 'Đang tải subagent…',
    'load.error': 'Không thể tải subagent',
    'retry': 'Thử lại',
    'mode.oneShot': 'Tác vụ một lần (one-shot)',
    'mode.continuable': 'Có thể tiếp tục (continuable)',
    'mode.unknown': 'chế độ không xác định',
    'readonly.unknown.body': 'Cần đọc dữ liệu phiên con để xác định có thể gửi tiếp hay không.',
    'activity.running': 'đang chạy',
    'activity.completed': 'đã hoàn tất',
    'activity.inactive': 'không hoạt động',
    'branch.collapse': 'Thu gọn các subagent cấp dưới của {label}',
    'branch.expand': 'Mở rộng các subagent cấp dưới của {label}',
    'count.total.one': '{count} subagent',
    'count.total.other': '{count} subagent',
    'count.running.one': '{count} subagent đang chạy',
    'count.running.other': '{count} subagent đang chạy',
    'switcher.aria': 'Chuyển đổi subagent: {title}',
    'tree.aria': 'Cây phân cấp phiên subagent',
    'open.sidebar': 'Mở {label} ở thanh bên',
    'sidebar.chat': 'Trò chuyện',
    'readonly.oneShot.title': 'Bản ghi subagent chạy một lần',
    'readonly.title': 'Subagent này hiện ở trạng thái chỉ đọc',
    'readonly.oneShot.body': 'Tác vụ chạy một lần không nhận thêm tin nhắn tiếp theo; bạn có thể xem lại toàn bộ nhật ký thực thi tại đây.',
    'readonly.body': 'Phiên cha hiện đang ngoại tuyến; hãy mở lại phiên cha để tiếp tục gửi tin nhắn.',
  },
  'workflowRun': {
    'run.title': '{name}',
    'run.members.one': '{count} thành viên',
    'run.members.other': '{count} thành viên',
    'run.empty': 'Chưa có thành viên nào được khởi chạy',
    'phase.unassigned': 'Chưa phân chia giai đoạn (phase)',
    'phase.empty': 'Tên giai đoạn trống',
    'statusCount.running': 'Đang chạy {count}',
    'statusCount.completed': 'Đã hoàn tất {count}',
    'statusCount.failed': 'Thất bại {count}',
    'statusCount.cancelled': 'Đã hủy {count}',
    'statusCount.interrupted': 'Đã ngắt {count}',
    'member.empty': 'Tên thành viên trống',
    'member.open': 'Mở {name}',
    'status.running': 'Đang chạy',
    'status.completed': 'Đã hoàn tất',
    'status.failed': 'Thất bại',
    'status.cancelled': 'Đã hủy',
    'status.interrupted': 'Đã ngắt',
  },
  'settings': {
    'trigger': 'Cài đặt',
    'desktop.update.available': 'Bản cập nhật mới',
    'desktop.update.checking': 'Đang kiểm tra cập nhật…',
    'desktop.update.progress': '{percent}%…',
    'desktop.update.verifying': 'Đang xác thực gói cập nhật…',
    'desktop.update.installing': 'Đang chuẩn bị khởi động lại…',
    'desktop.update.ready': 'Cài đặt và Khởi động lại',
    'desktop.update.retry': 'Thử cập nhật lại',
    'desktop.update.versionDetail': '{label} — V{version}',
    'desktop.update.downloadDetail': 'Đang tải bản cập nhật: {percent}%\nPhiên bản đích: V{version}',
    'desktop.update.checkFailed': 'Kiểm tra cập nhật thất bại, vui lòng thử lại sau.',
    'desktop.update.downloadFailed': 'Tải bản cập nhật thất bại, vui lòng thử lại.',
    'desktop.update.installFailed': 'Cài đặt cập nhật thất bại, vui lòng thử lại sau.',
    'desktop.update.checkNetworkFailed': 'Kiểm tra cập nhật thất bại. Kết nối mạng bị gián đoạn, vui lòng kiểm tra mạng và thử lại.',
    'desktop.update.downloadNetworkFailed': 'Tải bản cập nhật thất bại. Kết nối mạng bị gián đoạn, vui lòng kiểm tra mạng và thử lại.',
    'desktop.update.installNetworkFailed': 'Cài đặt cập nhật thất bại. Kết nối mạng bị gián đoạn, vui lòng kiểm tra mạng và thử lại.',
    'desktop.update.stopFailed': 'Không thể dừng an toàn các tác vụ đang chạy, bản cập nhật chưa được cài. Vui lòng thử lại sau.',
    'desktop.update.tasksChanged': 'Có tác vụ mới vừa bắt đầu, vui lòng xác nhận cập nhật lại.',
    'desktop.update.tasksUnavailable': 'Không thể xác định trạng thái tác vụ; hãy thử cập nhật lại sau khi workspace sẵn sàng.',
    'title': 'Cài đặt',
    'close': 'Đóng',
    'openDocument': 'Mở tệp cấu hình (settings.yaml)',
    'openDocument.error': 'Không thể mở tệp cấu hình',
    'general.nav': 'Cài đặt chung',
    'general.currentVersion': 'Phiên bản hiện tại: {version}',
    'developerTools.title': 'Công cụ nhà phát triển (Developer tools)',
    'developerTools.error': 'Lưu thất bại, vui lòng thử lại',
    'developerTools.description': 'Hiển thị các công cụ và thông tin phục vụ việc gỡ lỗi và chẩn đoán sự cố',
    'connection.error': 'Mất kết nối',
    'connection.connecting': 'Đang kết nối lại…',
    'connection.connected': 'Đã kết nối',
    'connection.reconnect': 'Mất kết nối, nhấp để kết nối lại',
    'connection.restart': 'Đang kết nối lại, nhấp để kết nối ngay',
  },
  'settings.account': {
    'close': 'Đóng',
    'addApiKey': 'Thêm API Key',
    'retry': 'Đăng nhập lại',
    'loginTitle': 'Bắt đầu sáng tạo',
    'loginDescription': 'Đăng nhập để tạo, chỉnh sửa và chia sẻ các dự án của bạn. Mọi dữ liệu được lưu cục bộ.',
    'browserTitle': 'Đang chờ đăng nhập',
    'browserPrompt': 'Trình duyệt không tự động mở? ',
    'copyLink': 'Sao chép liên kết đăng nhập',
    'copiedLink': 'Đã sao chép liên kết',
    'copyFailed': 'Sao chép thất bại',
    'browserDescription': ', sau đó mở liên kết trong trình duyệt để hoàn tất đăng nhập.',
    'timeoutTitle': 'Đăng nhập đã hết thời gian (timeout)',
    'timeoutDescription': 'Vui lòng đăng nhập lại để tiếp tục.',
    'failureTitle': 'Đăng nhập thất bại',
    'platformFailed': 'Thao tác chưa hoàn thành, vui lòng thử lại',
    'platformRetry': 'Thử lại',
    'loading': 'Đang tải…',
    'backToHarness': 'Quay lại DeepSeek Harness',
    'settings': 'Cài đặt',
    'contactUs': 'Liên hệ chúng tôi',
    'menu': 'Menu tài khoản',
    'nav': 'Tài khoản & số dư',
    'signedIn': 'Đã đăng nhập DeepSeek',
    'signedOut': 'Chưa đăng nhập',
    'signIn': 'Đăng nhập',
    'signOut': 'Đăng xuất',
    'cancel': 'Hủy',
    'open': 'Mở trình duyệt',
    'initializing': 'Đang khởi tạo phiên đăng nhập…',
    'waiting': 'Vui lòng tiếp tục thao tác trong trình duyệt',
    'completing': 'Đang hoàn tất đăng nhập…',
    'expired': 'Phiên đăng nhập đã hết hạn, vui lòng thử lại.',
    'failed': 'Thao tác thất bại, vui lòng thử lại.',
    'settingsSignedOutTitle': 'Hiện chưa đăng nhập tài khoản DeepSeek Harness',
    'settingsSignedOutDescription': 'Đăng nhập tài khoản DeepSeek Harness để nhận API Key chuyên dụng',
    'signInDescription': 'Đăng nhập bằng tài khoản DeepSeek để bắt đầu sử dụng',
    'profileUnavailable': 'Thông tin tài khoản tạm thời chưa khả dụng',
    'balance': 'Số dư nạp',
    'bonusBalance': 'Số dư khuyến mãi',
    'balanceUnavailable': 'Xem trên Nền tảng mở (Open Platform)',
    'balanceSignedOut': 'Đăng nhập để xem',
    'accountInfo': 'Xem thêm thông tin tài khoản',
    'more': 'Thêm',
    'usage': 'Tra cứu mức sử dụng',
    'topUp': 'Nạp tiền',
  },
  'settings.agentLoop': {
    'title': 'Vòng lặp Agent (Agent loop)',
    'description': 'Kiểm soát cách Agent điều phối và gửi các lệnh gọi công cụ.',
    'maxParallel': 'Số công cụ chạy song song tối đa',
    'maxParallelHint': 'Giới hạn trên cho số lượt gọi công cụ an toàn có thể chạy đồng thời trong cùng một bước (step).',
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cấu hình ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'invalidNumber': 'Vui lòng nhập một số hợp lệ, hoặc để trống để dùng giá trị mặc định.',
  },
  'settings.agentPreset': {
    'builtInGroup': 'Tích hợp sẵn (Built-in)',
    'customGroup': 'Tùy chỉnh (Custom)',
    'sectionIntro': 'Chọn bộ công cụ và phương thức làm việc của Agent. Dùng "Chế độ chuẩn" cho tác vụ thông thường hàng ngày, hoặc "Chế độ sáng tạo" để mở rộng năng lực DSH.',
    'seatHint': 'Chọn preset Agent cho tác vụ mới của bạn',
    'headerHint': 'Preset Agent được cố định từ khi tác vụ này bắt đầu',
    'nav': 'Preset Agent',
    'setDefault': 'Đặt làm mặc định cho tác vụ mới',
    'presetStandardName': 'Chế độ chuẩn (Standard mode)',
    'presetStandardDescription': 'Xử lý mã nguồn, tệp tin và tài liệu; phù hợp cho phần lớn tác vụ với đầy đủ công cụ tìm kiếm, chỉnh sửa và terminal khi cần.',
    'presetPtcName': 'Chế độ PTC (Programmatic Tool Calling)',
    'presetPtcDescription': 'Bao gồm toàn bộ năng lực của chế độ Chuẩn; tối ưu hơn cho các tác vụ cần gọi công cụ theo lô (batch) rồi lọc, xử lý, thống kê hoặc tổng hợp kết quả.',
    'presetMinimalName': 'Chế độ tối giản (Minimal mode)',
    'presetMinimalDescription': 'Agent chỉ sử dụng công cụ terminal để hoàn thành tác vụ; phù hợp cho kiểm thử chuẩn (benchmark) và so sánh hiệu năng cơ bản.',
    'presetCordisName': 'Chế độ sáng tạo (Creator mode)',
    'presetCordisDescription': 'Tùy biến DSH thông qua đối thoại: để Agent lập trình plugin bổ sung tính năng hoặc giao diện; kết hợp công cụ và prompt để tạo preset riêng.',
    'inUse': 'Mặc định cho tác vụ mới',
    'selectionOffDefault': 'Mặc định của ứng dụng',
    'noDescription': 'Chưa có mô tả.',
    'brokenBadge': 'Tải thất bại',
    'switchRefused': 'Không thể chuyển sang "{name}": {reason}',
    'close': 'Đóng',
    'creatorDraft': 'Để Agent giúp tôi tạo một chế độ preset mới',
    'showPicker': 'Cho phép chọn chế độ cho tác vụ mới',
    'showPickerBeta': 'Beta',
    'showPickerDescription': 'Khi bật, mỗi tác vụ mới có thể chọn chế độ và đặt mặc định tại đây. Khi tắt, tác vụ mới dùng preset mặc định của ứng dụng. Tác vụ hiện có không bị ảnh hưởng.',
    'enablePickerToSetDefault': 'Vui lòng bật tính năng chọn chế độ cho tác vụ mới trước khi đặt mặc định',
    'enablePickerToCreate': 'Vui lòng bật tính năng chọn chế độ cho tác vụ mới trước khi khởi động Chế độ sáng tạo',
    'modeExplanation': 'Chi tiết chế độ',
    'howToUse': 'Cách sử dụng',
    'guideSections': 'Các mục hướng dẫn',
    'guideExampleTask': 'Tác vụ mẫu',
    'guideCopy': 'Sao chép',
    'guideCopied': 'Đã sao chép',
    'guideFootnotes': 'Ghi chú',
  },
  'settings.permission': {
    'title': 'Quyền hạn (Permissions)',
    'description': 'Chọn chế độ quyền hạn mặc định cho các phiên làm việc mới',
    'loading': 'Đang tải…',
    'unavailable': 'Không khả dụng',
    'preset.readOnly': 'Chỉ xem (Read Only)',
    'preset.workspaceWrite': 'Ghi trong Workspace (Workspace Write)',
    'preset.fullAccess': 'Toàn quyền (Full Access)',
    'confirm.title': 'Xác nhận bật Toàn quyền (Full Access)?',
    'confirm.description': 'Khi kích hoạt Full Access, các phiên mới sẽ giảm thiểu các bước xác nhận và có thể trực tiếp thực thi nhiều thao tác hơn, bao gồm thao tác nhạy cảm, chỉnh sửa tệp hoặc chạy lệnh hệ thống bên ngoài. Chỉ nên kích hoạt khi bạn tin tưởng các tác vụ tiếp theo.',
    'confirm.acknowledge': 'Tôi hiểu rõ các rủi ro và muốn tiếp tục',
    'confirm.cancel': 'Hủy',
    'confirm.enable': 'Bật Toàn quyền',
  },
  'settings.pluginInventory': {
    'tab': 'Danh mục plugin',
    'loading': 'Đang nạp danh sách plugin…',
    'clientSyncing': 'Đang đồng bộ plugin trên trang này…',
    'clientSyncFailed': 'Một số plugin không thể đồng bộ trên trang này. Trạng thái kích hoạt trên máy chủ giữ nguyên.',
    'clientSyncRetry': 'Thử lại đồng bộ trang này',
    'error': 'Dịch vụ plugin tạm thời không khả dụng.',
    'metadataError': 'Lỗi siêu dữ liệu gói: {error}',
    'retry': 'Thử lại',
    'search': 'Tìm kiếm plugin…',
    'empty': 'Chưa có plugin nào.',
    'emptySearch': 'Không tìm thấy plugin phù hợp.',
    'presetTitle': 'Plugin theo phiên',
    'presetSubtitle': 'Được cấu thành theo từng phiên bởi preset Agent',
    'countUnit': 'plugin',
    'switcherLabel': 'Chọn preset Agent để kiểm tra',
    'presetOptionDefault': '{name} (mặc định)',
    'presetOptionBroken': '{name} (tải thất bại)',
    'globalTitle': 'Plugin toàn cục',
    'globalSubtitle': 'Dùng chung cho toàn hệ thống và tất cả các phiên',
    'presetProvidedDetail': 'Đã tắt toàn cục; được cung cấp theo từng phiên bởi preset Agent',
    'enabledIn': 'Được kích hoạt trong',
    'viewInPreset': 'Xem trong nhóm preset',
    'matchesInOtherPresets': 'Còn {count} kết quả phù hợp trong các preset khác: ',
    'failedCountLabel': 'thất bại',
    'enabledTag': 'Đã kích hoạt',
    'disabledTag': 'Đã tắt',
    'conditionalTag': 'Kích hoạt có điều kiện',
    'presetEnabledTag': 'Kích hoạt qua preset',
    'failedTag': 'Khởi động thất bại',
    'moduleLabel': 'Tên gói / Module',
    'fromPreset': 'Nguồn gốc',
    'condition': 'Điều kiện vô hiệu hóa',
    'configuration': 'Cấu hình',
    'runtime': 'Trạng thái runtime',
    'unobserved': 'Chưa chạy',
    'pending': 'Đang chờ phụ thuộc',
    'loadingPhase': 'Đang nạp',
    'active': 'Đang chạy',
    'failed': 'Khởi động thất bại',
    'unloading': 'Đang gỡ bỏ',
  },
  'settings.plugins': {
    'nav': 'Plugin tích hợp',
    'title': 'Plugin tích hợp',
    'intro': 'Xem danh sách các plugin đi kèm bản triển khai này.',
    'tabs': 'Chế độ xem plugin',
    'empty': 'Bản triển khai này không hiển thị chế độ xem plugin nào.',
  },
  'settings.shell': {
    'title': 'Shell / Terminal',
    'description': 'Giới hạn thời gian chạy tối đa (timeout) và dung lượng đầu ra của mỗi lệnh.',
    'timeoutMs': 'Thời gian chờ lệnh (ms)',
    'timeoutMsHint': 'Một lệnh được phép chạy trong bao lâu trước khi bị cưỡng chế kết thúc.',
    'maxOutputBytes': 'Giới hạn đầu ra mỗi luồng (Bytes)',
    'maxOutputBytesHint': 'Phần đầu ra vượt quá mức này sẽ được chuyển lưu vào tệp tạm (spill) thay vì bị cắt bỏ.',
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'invalidNumber': 'Vui lòng nhập một số hợp lệ, hoặc để trống để dùng giá trị mặc định.',
  },
  'settings.subagent': {
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'subagentTitle': 'Subagent',
    'subagentDescription': 'Thiết lập độ sâu đệ quy, số lượng và mô hình của Subagent.',
    'subagentLimitsTitle': 'Giới hạn Subagent',
    'subagentMaxDepth': 'Độ sâu đệ quy tối đa (Recursion depth)',
    'subagentDepthHelpLabel': 'Giải thích về độ sâu đệ quy tối đa',
    'subagentDepthHelp': 'Giới hạn số tầng Subagent mà một Agent có thể sinh ra.',
    'subagentDepthZero': 'Vô hiệu hóa Subagent',
    'subagentDepthOne': 'Chỉ Agent chính mới được tạo Subagent',
    'subagentDepthOverride': 'Nếu một công cụ có cấu hình độ sâu đệ quy riêng, thiết lập của công cụ đó sẽ được ưu tiên.',
    'subagentMaxActive': 'Giới hạn số Subagent chạy song song (Parallelism limit)',
    'subagentCapacityHelpLabel': 'Giải thích về giới hạn Subagent song song',
    'subagentCapacityHelp': 'Tổng số Subagent hoạt động đồng thời dưới cùng một Agent chính, trên mọi tầng đệ quy (không tính Agent chính). Khi chạm giới hạn, các yêu cầu khởi chạy mới sẽ bị từ chối.',
    'subagentDepthInvalid': 'Vui lòng nhập một số nguyên không âm (từ 0 trở lên).',
    'subagentCapacityInvalid': 'Vui lòng nhập một số nguyên dương (từ 1 trở lên).',
    'subagentModelSelectionTitle': 'Lựa chọn mô hình cho Subagent',
    'subagentModelSelectionToggle': 'Cho phép Agent tự chọn mô hình cho Subagent',
    'subagentModelSelectionChoose': 'Khi bật, Agent có thể chọn provider, model và mức độ suy luận cho từng Subagent từ danh sách được phân quyền bên dưới. Chỉ áp dụng cho các phiên mới.',
    'subagentModelSelectionAllowed': 'Các mô hình Agent được phép chọn',
    'subagentModelSelectionLoading': 'Đang tải danh sách mô hình…',
    'subagentModelSelectionLoadFailed': 'Không thể tải danh sách mô hình.',
    'subagentModelSelectionRetry': 'Thử lại',
    'subagentModelSelectionPartial': 'Một số nhà cung cấp mô hình tạm thời không thể tải; các lựa chọn đã lưu vẫn có thể xóa.',
    'subagentModelSelectionUnavailable': 'Hiện không khả dụng',
    'subagentModelSelectionUnavailableGroup': 'Đã lưu nhưng hiện không khả dụng',
    'subagentModelSelectionEmpty': 'Hiện không có nhà cung cấp nào công bố mô hình.',
    'subagentModelSelectionRequired': 'Vui lòng chọn ít nhất một mô hình trước khi lưu.',
    'subagentModelSelectionConflict': 'Cài đặt đã thay đổi ở nơi khác. Hãy làm mới và thử lại.',
    'subagentModelSelectionOff': 'Khi tắt, Subagent sẽ dùng mô hình mặc định hoặc kế thừa mô hình của Agent cha; các lựa chọn đã lưu vẫn được bảo lưu.',
  },
  'settings.webSearch': {
    'title': 'Tìm kiếm web (Web search)',
    'description': 'Cấu hình nhà cung cấp dịch vụ tìm kiếm web cho DeepSeek.',
    'apiKey': 'API Key',
    'apiKeyHint': 'Lưu trữ riêng biệt ngoài tệp cài đặt. Để trống để giữ khóa hiện tại.',
    'apiKeySet': 'Đã cấu hình API Key.',
    'apiKeyUnset': 'Chưa cấu hình API Key; tính năng tìm kiếm web tạm thời không khả dụng.',
    'baseUrl': 'Endpoint API',
    'baseUrlHint': 'Để trống để dùng địa chỉ mặc định của nhà cung cấp.',
    'maxUses': 'Số lượt tìm kiếm tối đa mỗi yêu cầu',
    'maxUsesHint': 'Số lần tối đa mà một yêu cầu có thể tìm kiếm web trước khi bắt buộc phải đưa ra câu trả lời.',
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'invalidNumber': 'Vui lòng nhập một số hợp lệ, hoặc để trống để dùng giá trị mặc định.',
  },
  'sidebar': {
    'session.new': 'Phiên mới',
    'session.new.label': 'Tạo phiên hội thoại mới',
    'toggle.open': 'Mở thanh bên',
    'toggle.collapse': 'Thu gọn thanh bên',
    'panels.label': 'Bảng điều khiển toàn cục',
  },
  'sidebarBrowser': {
    'type.label': 'Trình duyệt nhúng',
    'guide.title': 'Trình duyệt web',
    'guide.description': 'Duyệt các trang web trực tiếp trong DSH',
    'address.placeholder': 'Nhập địa chỉ HTTP(S)…',
    'address.changed': 'URL đã thay đổi',
    'back': 'Quay lại',
    'forward': 'Tiến lên',
    'reload': 'Tải lại trang',
    'go': 'Truy cập',
    'external': 'Mở trong trình duyệt hệ thống',
    'sandbox.disable': 'Tắt giới hạn sandbox',
    'sandbox.enable': 'Bật lại giới hạn sandbox',
    'sandbox.warning': 'Giới hạn sandbox đã tắt; trang web có thể điều hướng ứng dụng cấp cao nhất, tải tệp, hiển thị modal và khóa con trỏ/nhập liệu.',
    'start': 'Nhập địa chỉ HTTP(S) để bắt đầu duyệt web',
    'loading': 'Đang mở trang…',
    'restore.previous': 'Trang đã mở lần trước',
    'restore.action': 'Khôi phục trang',
    'error.empty': 'Vui lòng nhập địa chỉ URL.',
    'error.invalid': 'Địa chỉ này không hợp lệ hoặc quá dài.',
    'error.protocol': 'Chỉ hỗ trợ giao thức HTTP và HTTPS; tệp cục bộ vui lòng dùng tính năng Xem trước tài liệu.',
    'error.credentials': 'Địa chỉ URL không được chứa tên người dùng hoặc mật khẩu.',
    'error.application-origin': 'Trình duyệt nhúng không thể mở chính ứng dụng DSH.',
    'load.failed': 'Tải trang thất bại; vui lòng làm mới hoặc mở trong trình duyệt hệ thống.',
    'load.failed.detail': 'Tải trang thất bại ({code}): {description}',
    'address.unknown': 'Trang web đã điều hướng; môi trường hiện tại không thể đọc URL mới.',
  },
  'sidebarFiles': {
    'type.label': 'Tệp tin',
    'guide.title': 'Tệp trong Workspace',
    'guide.description': 'Duyệt các tệp trong workspace của phiên hiện tại',
    'loading': 'Đang đọc danh sách tệp…',
    'empty': 'Thư mục trống',
    'truncated': 'Có quá nhiều mục, chỉ hiển thị một phần.',
    'noWorkspace': 'Phiên làm việc này không có thư mục workspace.',
    'reload': 'Tải lại',
    'autoRefresh': 'Tự động làm mới',
    'autoRefresh.enable': 'Bật tự động làm mới',
    'autoRefresh.disable': 'Tắt tự động làm mới',
    'entry.other': 'Đây không phải tệp hoặc thư mục hợp lệ để mở.',
    'error.notFound': 'Thư mục này không còn tồn tại. Có thể đã bị di chuyển hoặc xóa.',
    'error.outsideWorkspace': 'Thư mục này nằm ngoài workspace nên thanh bên sẽ từ chối đọc.',
    'error.notDirectory': 'Đây không phải là một thư mục.',
    'error.unavailable': 'Đọc thư mục thất bại: {message}',
  },
  'sidebarRight': {
    'chrome.expand': 'Mở thanh bên',
    'chrome.expandAria': 'Mở thanh bên phải',
    'chrome.collapse': 'Thu gọn thanh bên',
    'chrome.collapseAria': 'Thu gọn thanh bên phải',
    'chrome.toFullscreen': 'Toàn màn hình',
    'chrome.exitFullscreen': 'Thoát toàn màn hình',
    'dock.emptyPane': 'Khung trống',
    'dock.splitPane': 'Chia cột (Split)',
    'dock.splitPaneDisabled': 'Đã đạt giới hạn tối đa hai cột',
    'dock.splitPaneNarrow': 'Chiều rộng thanh bên không đủ để chia cột; vui lòng kéo rộng thanh bên',
    'dock.closeTab': 'Đóng thẻ',
    'dock.addTab': 'Thẻ mới',
    'dock.dockFloat': 'Ghim lại vào thanh bên',
    'dock.closeFloat': 'Đóng cửa sổ nổi',
    'dock.drop.center': 'Di chuyển vào đây',
    'dock.drop.left': 'Thêm cột bên trái',
    'dock.drop.right': 'Thêm cột bên phải',
    'dock.drop.top': 'Thêm hàng phía trên',
    'dock.drop.bottom': 'Thêm hàng phía dưới',
    'tab.guide.title': 'Bắt đầu',
    'tab.unavailable': 'Chưa có trình xem nào hỗ trợ định dạng nội dung này.',
  },
  'sidebarTerminal': {
    'recoveryFailed': 'Khôi phục terminal thất bại: {message}',
    'retryRecovery': 'Thử lại khôi phục terminal',
    'shell': 'Chọn Shell',
    'shellLoading': 'Đang tải danh sách Shell…',
    'shellEmpty': 'Không có Shell nào khả dụng',
    'description': 'Chạy lệnh dòng lệnh trong workspace của phiên',
    'title': 'Terminal',
    'new': 'Terminal mới',
    'loading': 'Đang nạp môi trường terminal…',
    'creating': 'Đang khởi động terminal…',
    'connecting': 'Đang kết nối terminal…',
    'disconnected': 'Kết nối terminal đã ngắt.',
    'reconnect': 'Kết nối lại',
    'readonly': 'Giao diện terminal này hiện chỉ đọc.',
    'control': 'Tiếp quản nhập liệu',
    'closed': 'Terminal đã đóng.',
    'exited': 'Tiến trình terminal đã thoát (mã {code})',
    'failed': 'Lỗi terminal: {message}',
    'rename': 'Đổi tên terminal',
    'unavailable': 'Không khả dụng',
    'retry': 'Thử lại',
    'cleanupFailed': 'Không thể kết thúc terminal "{title}": {message}',
    'missingTerminal': 'Terminal này không còn tồn tại, vui lòng mở terminal mới.',
    'inputFull': 'Bộ đệm nhập liệu đã đầy, hãy kết nối lại rồi thử lại.',
    'attachmentEnded': 'Kết nối terminal đã kết thúc; hãy kết nối lại.',
    'invalidOutput': 'Truyền tải màn hình terminal bị lỗi; hãy kết nối lại.',
    'terminalLimit': 'Đã đạt giới hạn số lượng terminal tối đa. Vui lòng đóng bớt terminal không dùng (các terminal đã thoát vẫn tính vào giới hạn).',
  },
  'sidebarDocumentPreview': {
    'loading': 'Đang đọc nội dung…',
    'loadMore': 'Tải thêm nội dung',
    'changed': 'Tệp đã thay đổi từ bên ngoài, đang hiển thị nội dung phiên bản trước',
    'reloadNow': 'Tải lại ngay',
    'reload': 'Đọc lại tệp',
    'autoRefresh': 'Tự động làm mới',
    'autoRefresh.enable': 'Bật tự động làm mới',
    'autoRefresh.disable': 'Tắt tự động làm mới',
    'wrap.enable': 'Bật tự động xuống dòng (Word wrap)',
    'wrap.disable': 'Tắt tự động xuống dòng',
    'wrap.aria': 'Tự động xuống dòng',
    'openWith': 'Mở bằng ứng dụng',
    'viewer.text': 'Văn bản thuần (Plain text)',
    'resourceUnavailable': 'Dịch vụ tài nguyên tệp không khả dụng',
    'rendererUnavailable': 'Trình xem trước {name} không khả dụng',
    'unsupportedFile': 'Định dạng tệp này tạm thời chưa được hỗ trợ xem trước',
    'error.notFound': 'Tệp không tồn tại; có thể đã bị di chuyển hoặc xóa',
    'error.tooLarge': 'Nội dung trang vượt quá giới hạn {limit}, không thể nạp',
    'error.notText': 'Định dạng tệp này không phải văn bản thuần để xem trước',
    'error.notRegularFile': 'Đường dẫn này không phải tệp thông thường (regular file), không có nội dung hiển thị',
    'error.unavailable': 'Đọc tệp thất bại: {message}',
    'retry': 'Thử lại',
  },
  'sidebarCodePreview': {
    'title': 'Mã nguồn (Code)',
    'copy': 'Sao chép mã',
    'copied': 'Đã sao chép mã',
  },
  'sidebarExcel': {
    'title': 'Bảng tính (Spreadsheet)',
    'language': 'vi',
    'loading': 'Đang mở bảng tính…',
    'invalid': 'Không thể mở bảng tính này. Hãy kiểm tra định dạng tệp, cấu trúc hoặc mật khẩu bảo vệ.',
    'tooLarge': 'Bảng tính này vượt quá giới hạn kích thước xem trước.',
    'timeout': 'Mở bảng tính bị quá thời gian (timeout). Hãy thử với tệp nhỏ hơn.',
    'encoding': 'Không thể nhận dạng mã hóa văn bản. Hãy lưu tệp dưới dạng UTF-8 hoặc UTF-16 có BOM rồi thử lại.',
    'formulaWarning': 'Bảng tính có chứa công thức; kết quả hiển thị có thể bị thiếu hoặc chưa chuẩn xác.',
    'unsupportedNotice': 'Trình xem trước chưa hỗ trợ các thành phần {features} trong tệp này. Hãy mở bằng ứng dụng chuyên dụng để có trải nghiệm đầy đủ.',
    'charts': 'biểu đồ',
    'images': 'hình ảnh',
    'shapes': 'hình vẽ',
    'conditionalFormatting': 'định dạng có điều kiện',
    'featureSeparator': ', ',
    'retry': 'Thử lại',
  },
  'sidebarImage': {
    'zoomControls': 'Điều khiển thu phóng (Zoom)',
    'zoomMenu': 'Chọn tỷ lệ thu phóng',
    'zoomOut': 'Thu nhỏ',
    'zoomIn': 'Phóng to',
    'zoomFitWidth': 'Vừa chiều rộng (Fit width)',
    'zoomValue': '{percent}%',
    'title': 'Hình ảnh',
    'preview': 'Xem trước ảnh: {name}',
    'loading': 'Đang nạp ảnh…',
    'failed': 'Không thể hiển thị hình ảnh này',
    'unsupported': 'Xem trước hình ảnh yêu cầu toàn bộ nội dung tệp',
  },
  'sidebarOffice': {
    'title': 'Tài liệu Office',
    'loading': 'Đang nạp tài liệu Office…',
    'retry': 'Thử lại',
    'viewMissingFonts': 'Thiếu {count} phông chữ, nhấp để xem chi tiết',
    'missingFontsTitle': 'Phông chữ bị thiếu',
    'missingFontsDescription': 'Bản xem trước không có các phông chữ này; định dạng chữ và bố cục có thể khác so với tài liệu gốc.',
    'missingFontsCount': '{count} phông chữ',
    'closeDetails': 'Đóng chi tiết phông chữ',
    'unavailable': 'Tính năng xem trước Office không khả dụng. Vui lòng bật dịch vụ xem trước tài liệu trên máy chủ chạy DeepSeek Harness.',
    'invalid': 'Không thể xem trước tệp Office này. Tệp có thể bị hỏng, có mật khẩu bảo vệ hoặc sai định dạng mở rộng.',
    'tooLarge': 'Tệp Office hoặc PDF sau chuyển đổi vượt quá giới hạn kích thước xem trước. Hãy giảm dung lượng tệp hoặc điều chỉnh cấu hình xem trước.',
    'failed': 'Chuyển đổi Office thất bại, không tạo được PDF khả dụng. Vui lòng kiểm tra lại tệp nguồn.',
    'timeout': 'Chuyển đổi Office bị quá thời gian (timeout), vui lòng thử lại.',
    'busy': 'Hàng đợi xem trước Office đang bận, vui lòng thử lại sau ít phút.',
    'changed': 'Tệp đã thay đổi trong khi đang đọc. Vui lòng mở lại bản xem trước.',
  },
  'sidebarPdf': {
    'zoomControls': 'Điều khiển thu phóng (Zoom)',
    'zoomMenu': 'Chọn tỷ lệ thu phóng',
    'zoomOut': 'Thu nhỏ',
    'zoomIn': 'Phóng to',
    'zoomFitWidth': 'Vừa chiều rộng (Fit width)',
    'zoomValue': '{percent}%',
    'title': 'Tài liệu PDF',
    'pageImage': 'Trang PDF {page}',
    'loading': 'Đang nạp PDF…',
    'rendering': 'Đang kết xuất trang…',
    'failed': 'Không thể hiển thị PDF: {message}',
    'password': 'Tệp PDF này có mật khẩu bảo vệ; hiện chưa hỗ trợ xem trước tệp có mật khẩu.',
    'workerFailed': 'Tiến trình kết xuất PDF (worker) gặp sự cố; vui lòng thử lại.',
    'unsupported': 'Xem trước PDF yêu cầu toàn bộ nội dung tệp.',
    'retry': 'Thử lại',
  },
  'directory-browser': {
    'browser.title': 'Chọn thư mục Workspace',
    'browser.home': 'Thư mục Home',
    'browser.newFolder': 'Thư mục mới',
    'browser.folderName': 'Tên thư mục',
    'browser.createIn': 'Tạo thư mục mới trong "{name}"',
    'browser.untitledFolder': 'Thư mục không tên',
    'browser.create': 'Tạo',
    'browser.cancel': 'Hủy',
    'browser.open': 'Chọn mở',
    'browser.editPath': 'Chỉnh sửa đường dẫn',
    'browser.loading': 'Đang tải danh sách thư mục…',
    'browser.truncated': 'Quá nhiều thư mục; chỉ hiển thị phần đầu danh sách.',
    'browser.showHidden': 'Hiển thị tệp/thư mục ẩn',
  },
  'documentHtml': {
    'title': 'Tài liệu HTML',
    'frame': 'Khung xem trước tài liệu HTML',
    'loading': 'Đang nạp HTML…',
    'failed': 'Không thể xem trước tài liệu HTML này.',
  },
  'documentMarkdown': {
    'viewer.label': 'Markdown',
    'code.copy': 'Sao chép mã',
    'code.copied': 'Đã sao chép mã',
    'footnotes': 'Ghi chú cuối trang (Footnotes)',
  }
};

const allDicts = {
  ...core,
  ...convDicts,
  ...panelDicts,
  ...additionalDicts,
};

console.log(`Assembled ${Object.keys(allDicts).length} namespaces.`);

// Write features.ts and surfaces.ts back to harness for completeness
const featuresNames = [
  'approval', 'command', 'deliverables', 'feedback', 'goal', 'job', 'model',
  'open-in-app', 'permission.access', 'plan', 'question', 'reference',
  'schedule.catalog', 'skill', 'slash.menu', 'subagent', 'workflowRun'
];
const surfacesNames = [
  'settings', 'settings.account', 'settings.agentLoop', 'settings.agentPreset',
  'settings.permission', 'settings.pluginInventory', 'settings.plugins',
  'settings.shell', 'settings.subagent', 'settings.webSearch',
  'sidebar', 'sidebarBrowser', 'sidebarFiles', 'sidebarRight', 'sidebarTerminal',
  'sidebarDocumentPreview', 'sidebarCodePreview', 'sidebarExcel', 'sidebarImage',
  'sidebarOffice', 'sidebarPdf', 'directory-browser', 'documentHtml', 'documentMarkdown'
];

const featuresObj = {};
for (const n of featuresNames) {
  if (additionalDicts[n]) featuresObj[n] = additionalDicts[n];
}
const surfacesObj = {};
for (const n of surfacesNames) {
  if (additionalDicts[n]) surfacesObj[n] = additionalDicts[n];
}

fs.writeFileSync(
  'D:\\Project\\deepseek-harness\\packages\\client\\locale\\src\\locales\\vi\\features.ts',
  `/** Vietnamese shard: feature namespaces. */\nexport const dicts = ${JSON.stringify(featuresObj, null, 2)} satisfies Record<string, Record<string, string>>\n`
);

fs.writeFileSync(
  'D:\\Project\\deepseek-harness\\packages\\client\\locale\\src\\locales\\vi\\surfaces.ts',
  `/** Vietnamese shard: surfaces and settings namespaces. */\nexport const dicts = ${JSON.stringify(surfacesObj, null, 2)} satisfies Record<string, Record<string, string>>\n`
);

// Now generate the standalone plugin bundle: lib/client.js
const clientBundle = `/* global window, localStorage */
// lib/client.js — Vietnamese language pack for DeepSeek Harness Web UI
window.__ModuleLoader__.load({
  id: "dsh-vietnamese-lang",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;

    const name = "dsh-vietnamese-lang";
    const inject = ["locale"];

    const DICTS = ${JSON.stringify(allDicts, null, 2)};

    function apply(ctx) {
      const locale = ctx.get("locale");
      if (!locale || typeof locale.register !== "function") {
        console.warn("[dsh-vietnamese-lang] locale service unavailable");
        return;
      }

      // 1. Add Vietnamese language definition if addLanguage is supported
      if (typeof locale.addLanguage === "function") {
        try {
          ctx.effect(
            () => locale.addLanguage({ id: "vi", label: "Tiếng Việt", fallback: "en" }),
            "dsh-vietnamese-lang: language definition"
          );
        } catch (e) {
          // ignore if already added
        }
      }

      // 2. Register all Vietnamese dictionaries
      for (const [ns, dict] of Object.entries(DICTS)) {
        try {
          ctx.effect(
            () => locale.register(ns, "vi", dict),
            "dsh-vietnamese-lang: " + ns
          );
        } catch (error) {
          console.error("[dsh-vietnamese-lang] Failed to register " + ns, error);
        }
      }

      // 3. Fallback / patch snapshot if addLanguage is not natively in locale
      if (typeof locale.getLocale === "function") {
        const snap = locale.getLocale();
        const locales = snap.locales || snap.options || [];
        if (!locales.some((l) => l.id === "vi")) {
          const next = [...locales, { id: "vi", label: "Tiếng Việt" }];
          try {
            locale.snapshot = Object.freeze({
              ...snap,
              locales: Object.freeze(next),
              options: Object.freeze(next),
            });
            if (typeof locale.publish === "function") {
              locale.publish(snap.active, true);
            }
          } catch (_) {}
        }
      }

      // 4. Persistence with localStorage for smooth experience
      const STORAGE_KEY = "dsh-vietnamese-lang.preference";
      const readPref = () => {
        try { return localStorage.getItem(STORAGE_KEY); } catch (_) { return null; }
      };
      const writePref = (val) => {
        try {
          if (val) localStorage.setItem(STORAGE_KEY, val);
          else localStorage.removeItem(STORAGE_KEY);
        } catch (_) {}
      };

      if (typeof locale.setLocale === "function") {
        const origSet = locale.setLocale.bind(locale);
        locale.setLocale = (id) => {
          if (id === "vi") {
            writePref("vi");
            if (typeof locale.publish === "function") locale.publish("vi", true);
            else origSet("vi");
          } else {
            writePref(null);
            origSet(id);
          }
        };
      }

      const activateIfPreferred = () => {
        if (readPref() === "vi" && locale.getLocale().active !== "vi") {
          try {
            if (typeof locale.publish === "function") locale.publish("vi", true);
            else if (typeof locale.setLocale === "function") locale.setLocale("vi");
          } catch (_) {}
        }
      };

      if (typeof locale.adopt === "function") {
        const origAdopt = locale.adopt.bind(locale);
        locale.adopt = (host) => {
          origAdopt(host);
          activateIfPreferred();
        };
      }
      activateIfPreferred();
    }

    exports.name = name;
    exports.inject = inject;
    exports.apply = apply;
    return module.exports;
  }
});
`;

fs.writeFileSync('D:\\Project\\dsh-vietnamese-lang\\lib\\client.js', clientBundle);
console.log('Successfully wrote D:\\Project\\dsh-vietnamese-lang\\lib\\client.js');
