import fs from 'node:fs';
import path from 'node:path';

// Import existing translated namespaces
const { core } = await import('file:///D:/Project/deepseek-harness/packages/client/locale/src/locales/vi/core.ts');
const { dicts: convDicts } = await import('file:///D:/Project/deepseek-harness/packages/client/locale/src/locales/vi/conversation.ts');
const { dicts: panelDicts } = await import('file:///D:/Project/deepseek-harness/packages/client/locale/src/locales/vi/panels.ts');

// The remaining 41 namespaces translated to Vietnamese
const additionalDicts = {
  'approval': {
    'waiting': 'Đang chờ phê duyệt',
    'detail.aria': 'Chi tiết phê duyệt',
    'escalation': 'Công cụ {toolName} yêu cầu quyền thực thi mở rộng',
    'reject': 'Từ chối',
    'allowOnce': 'Cho phép một lần',
  },
  'command': {
    'section.add': 'Thêm',
    'section.commands': 'Lệnh',
    'label.goal': 'Mục tiêu',
    'label.plan': 'Kế hoạch',
    'label.feedback': 'Phản hồi',
    'label.compact': 'Nén hội thoại',
    'label.permission': 'Quyền hạn',
    'label.export': 'Tải xuống nhật ký',
    'description.goal': 'Thiết lập hoặc xem mục tiêu cho tác vụ dài hạn',
    'description.plan': 'Bật hoặc tắt chế độ lập kế hoạch',
    'description.feedback': 'Gửi phản hồi về phiên làm việc này',
    'description.compact': 'Nén nội dung lịch sử trò chuyện phía trên',
    'description.permission': 'Chuyển đổi cấu hình quyền hạn (chế độ sandbox và chính sách phê duyệt)',
    'description.export': 'Xuất nội dung phiên hiện tại thành tệp ZIP',
    'token.goal': 'mục tiêu',
    'token.plan': 'kế hoạch',
    'token.feedback': 'phản hồi',
    'token.compact': 'nén',
    'token.permission': 'quyền hạn',
    'token.export': 'xuất',
    'search.placeholder': 'Tìm kiếm…',
    'search.aria': 'Lọc tùy chọn',
    'status.loading': 'Đang tải tùy chọn…',
    'status.applying': 'Đang áp dụng…',
    'status.empty': 'Không có tùy chọn',
    'overlay.aria': 'Tùy chọn /{command}',
    'listbox.aria': 'Kết quả phù hợp /{command}',
    'notice.attachmentsUnsupported': '/{command} không chấp nhận tệp đính kèm, vui lòng gỡ tệp trước',
  },
  'deliverables': {
    'presented.nativeUnavailable': 'Tệp này không có đường dẫn khả dụng trên máy chủ, hãy xem trước ở thanh bên',
    'presented.revealError': 'Không thể hiển thị trong trình quản lý tệp, vui lòng thử lại',
    'presented.directoryError': 'Không thể mở thư mục chứa tệp, vui lòng thử lại',
    'presented.directoryOpening': 'Đang mở thư mục chứa tệp…',
    'presented.directoryOpened': 'Đã gửi yêu cầu mở thư mục chứa tệp',
    'presented.revealed': 'Đã gửi yêu cầu hiển thị trong trình quản lý tệp',
    'presented.revealing': 'Đang hiển thị trong trình quản lý tệp…',
    'presented.unavailable': 'Máy chủ này không có giao diện màn hình để mở bằng ứng dụng ngoài; bạn vẫn có thể xem trước trong thanh bên',
    'presented.retry': 'Thử lại',
    'presented.hostError': 'Không thể đọc thông tin màn hình máy chủ',
    'presented.preview': 'Xem trước ở thanh bên',
    'presented.previewButton': 'Mở {name} ở thanh bên',
    'presented.previewCard': 'Xem trước {name} ở thanh bên',
    'presented.all': 'Tất cả {count} tệp',
    'presented.expandAria': 'Mở rộng tất cả {count} tệp bàn giao',
    'presented.collapse': 'Thu gọn',
    'presented.collapseAria': 'Thu gọn danh sách tệp bàn giao',
    'presented.opening': 'Đang mở…',
    'presented.opened': 'Đã yêu cầu mở',
    'presented.error': 'Mở thất bại, nhấp để thử lại',
    'presented.file': 'Tệp',
    'row.title': 'Tệp bàn giao',
    'row.running': 'Đang bàn giao',
    'row.ok': 'Đã bàn giao',
    'row.error': 'Bàn giao thất bại',
    'row.stopped': 'Đã ngắt',
    'row.inspect': 'Xem chi tiết gọi',
    'changes.title': 'Đã sửa {count} tệp',
    'changes.added': '+{count}',
    'changes.deleted': '-{count}',
    'changes.binary': 'nhị phân',
    'changes.openReview': 'Xem các thay đổi của lượt này ở thanh bên',
    'changes.all': 'Tất cả {count} tệp',
    'changes.expandAria': 'Mở rộng tất cả {count} tệp thay đổi',
    'changes.collapse': 'Thu gọn',
    'changes.collapseAria': 'Thu gọn danh sách tệp thay đổi',
    'changes.oversized': 'quá lớn',
    'changes.viewDiff': 'Xem thay đổi của {name}',
    'review.title': 'Xem lại lượt {turn}',
    'review.selectFile': 'Chọn tệp muốn xem',
    'review.split': 'Chuyển sang chế độ so sánh hai cột',
    'review.unified': 'Chuyển sang chế độ so sánh đơn dòng',
    'review.splitAria': 'So sánh hai cột',
    'review.wrap': 'Bật tự động xuống dòng',
    'review.nowrap': 'Tắt tự động xuống dòng',
    'review.wrapAria': 'Tự động xuống dòng',
    'review.openFile': 'Mở toàn bộ tệp trong thanh bên',
    'review.openFileAria': 'Mở {name} trong thanh bên',
    'diff.loading': 'Đang đọc các thay đổi…',
    'diff.missing': 'Nội dung thay đổi của lượt này không còn khả dụng',
    'diff.error': 'Không thể đọc thay đổi',
    'diff.binary': 'Tệp nhị phân, không thể hiển thị khác biệt',
    'diff.oversized': 'Tệp quá lớn, không thể hiển thị khác biệt',
    'diff.created': 'Tệp tạo mới trong lượt này',
    'diff.deleted': 'Tệp đã xóa trong lượt này',
    'diff.unchanged': 'Nội dung hai bên giống nhau',
    'diff.coarse': 'Hết thời gian so sánh từng dòng; hiển thị thay thế toàn bộ tệp',
    'diff.truncated': 'Chỉ hiển thị {count} dòng đầu tiên',
  },
  'feedback': {
    'action.like': 'Câu trả lời tốt',
    'action.likeActive': 'Hủy đánh giá',
    'action.dislike': 'Câu trả lời có vấn đề',
    'action.dislikeActive': 'Hủy đánh giá',
    'dialog.title': 'Gửi phản hồi',
    'dialog.categories': 'Phân loại phản hồi',
    'dialog.detail': 'Chi tiết phản hồi',
    'dialog.hint': 'Điền chi tiết để giúp chúng tôi cải thiện trải nghiệm. Nội dung gửi sẽ bao gồm nhật ký của cuộc trò chuyện này.',
    'category.task-result': 'Kết quả tác vụ',
    'category.instruction-following': 'Hiểu và tuân thủ chỉ thị',
    'category.product-interaction': 'Tính năng và tương tác sản phẩm',
    'category.service-stability': 'Độ ổn định và tốc độ',
    'category.resource-cost': 'Mức sử dụng tài nguyên và chi phí',
    'category.security-privacy-permission': 'Bảo mật, quyền riêng tư và quyền hạn',
    'category.other': 'Khác',
    'toast.recorded': 'Cảm ơn phản hồi của bạn',
    'error.conflict': 'Phản hồi này đã được chỉnh sửa ở nơi khác; đang hiển thị trạng thái mới nhất',
    'error.load': 'Không thể tải trạng thái phản hồi',
    'error.generic': 'Lưu phản hồi thất bại',
    'error.noteTooLarge': 'Mô tả quá dài, vui lòng rút ngắn rồi gửi lại',
  },
  'goal': {
    'phase.active': 'Mục tiêu đang diễn ra',
    'phase.active.disarmed': 'Mục tiêu chưa kích hoạt',
    'phase.paused': 'Mục tiêu đã tạm dừng',
    'phase.blocked': 'Mục tiêu đang bị chặn',
    'objective.aria': 'Nội dung mục tiêu',
    'commandInput.aria': 'Nhập lệnh',
    'action.save': 'Lưu mục tiêu',
    'action.cancel': 'Hủy chỉnh sửa',
    'action.pause': 'Tạm dừng mục tiêu',
    'action.resume': 'Tiếp tục mục tiêu',
    'action.edit': 'Sửa mục tiêu',
    'action.clear': 'Xóa mục tiêu',
  },
  'job': {
    'count.live.one': '{count} tác vụ nền đang chạy',
    'count.live.other': '{count} tác vụ nền đang chạy',
    'count.idle.one': '{count} tác vụ nền',
    'count.idle.other': '{count} tác vụ nền',
    'list.aria': 'Tác vụ nền',
    'section.live': 'Đang chạy',
    'section.settledCount': 'Đã kết thúc {count}',
    'section.clear': 'Xóa sạch',
    'row.expandAria': 'Mở rộng đầu ra thời gian thực của {label}',
    'row.collapseAria': 'Thu gọn đầu ra thời gian thực của {label}',
    'kill.stop': 'Dừng tác vụ {label}',
    'kill.confirm': 'Nhấp lần nữa để xác nhận dừng',
    'kill.confirmAction': 'Xác nhận dừng',
    'kill.failed': 'Dừng thất bại',
    'status.running': 'đang chạy',
    'status.stopping': 'đang dừng',
    'status.completed': 'đã hoàn tất',
    'status.killed': 'đã hủy',
    'status.failed': 'thất bại',
    'duration.seconds': '{seconds}s',
    'duration.minutes': '{minutes}m {seconds}s',
    'duration.hours': '{hours}h {minutes}m',
    'duration.title.live': 'Đã chạy {duration}',
    'duration.title.done': 'Thời gian chạy {duration}',
    'output.gap': '… các đầu ra trước đó đã được lược bỏ …',
    'output.error': 'Luồng đầu ra thời gian thực bị gián đoạn: {error}',
    'terminal.signal': 'tín hiệu {signal}',
    'terminal.exitCode': 'mã thoát {code}',
    'terminal.noExitCode': 'không có mã thoát',
    'terminal.running': 'đang chạy',
    'terminal.failed': 'thất bại',
    'terminal.done': 'hoàn tất',
    'terminal.copy': 'Sao chép',
    'terminal.copied': 'Đã sao chép',
    'terminal.noOutput': '(không có đầu ra)',
    'terminal.collapse': 'Thu gọn',
    'terminal.collapseAria': 'Thu gọn đầu ra',
    'terminal.expand': 'Mở rộng thêm {n} dòng',
    'terminal.expandAria': 'Mở rộng {n} dòng đầu ra bị ẩn',
  },
  'model': {
    'command.label': 'Mô hình',
    'command.description': 'Chọn mô hình cho cuộc trò chuyện này',
    'option.loadError': 'Không thể tải danh mục: {message}',
    'option.deepseekV4Flash.description': 'Nhanh, hiệu quả và tiết kiệm; phù hợp với các tác vụ định hướng rõ ràng, thông thường hoặc song song.',
    'option.deepseekV4Pro.description': 'Khả năng lập trình tự động, kiến thức và suy luận phức tạp mạnh mẽ hơn; phù hợp với tác vụ phức tạp đòi hỏi chất lượng cao.',
    'trigger.fallback': 'Chọn mô hình',
    'trigger.loading': 'Đang tải mô hình…',
    'trigger.selectAria': 'Chọn mô hình',
    'trigger.aria': 'Chọn mô hình, hiện tại {model}',
    'trigger.ariaEffort': 'Chọn mô hình, hiện tại {model}, mức suy luận {effort}',
    'menu.aria': 'Mô hình và mức suy luận',
    'menu.model': 'Mô hình',
    'menu.effort': 'Mức suy luận',
    'effort.providerDefault': 'Mặc định',
    'status.loading': 'Đang làm mới danh sách mô hình…',
    'error.action': 'Thao tác mô hình thất bại: {message}',
    'error.sessionInUse': 'Phiên hiện tại đang được sử dụng bởi phiên bản DSH khác. Hãy đóng phiên bản đó và thử lại.',
    'action.reload': 'Tải lại',
    'warning.groupLoad': 'Tải {name} thất bại: {message}',
    'empty.models': 'Không có mô hình nào khả dụng.',
    'blocked.composer': 'Mô hình hiện tại không khả dụng — hãy chọn một mô hình để tiếp tục',
    'empty.efforts': 'Mô hình này không cung cấp các mức suy luận.',
  },
  'open-in-app': {
    'open.title': 'Mở bằng {app}',
    'path.appDefault': '{app} (mặc định)',
    'path.appsError': 'Không thể lấy danh sách ứng dụng',
    'path.open': 'Mở',
    'path.more': 'Thêm cách mở khác',
    'path.reveal': 'Hiển thị vị trí tệp',
    'path.openError': 'Mở thất bại, vui lòng thử lại',
    'path.revealError': 'Không thể hiển thị vị trí tệp, vui lòng thử lại',
    'app.cursor': 'Cursor',
    'app.vscode': 'VS Code',
    'app.vscodeinsiders': 'VS Code Insiders',
    'app.windsurf': 'Windsurf',
    'app.zed': 'Zed',
    'app.sublimetext': 'Sublime Text',
    'app.xcode': 'Xcode',
    'app.androidstudio': 'Android Studio',
    'app.intellij': 'IntelliJ IDEA',
    'app.pycharm': 'PyCharm',
    'app.webstorm': 'WebStorm',
    'app.phpstorm': 'PhpStorm',
    'app.goland': 'GoLand',
    'app.rider': 'Rider',
    'app.rustrover': 'RustRover',
    'app.fork': 'Fork',
    'app.sourcetree': 'Sourcetree',
    'app.github': 'GitHub Desktop',
    'app.tower': 'Tower',
    'app.gitkraken': 'GitKraken',
    'app.smartgit': 'SmartGit',
    'app.sublimemerge': 'Sublime Merge',
    'app.ghostty': 'Ghostty',
    'app.warp': 'Warp',
    'app.iterm': 'iTerm2',
    'app.kitty': 'kitty',
    'app.windowsterminal': 'Windows Terminal',
    'app.gitbash': 'Git Bash',
    'app.gnometerminal': 'GNOME Terminal',
    'app.konsole': 'Konsole',
    'app.finder': 'Finder',
    'app.explorer': 'File Explorer',
    'app.filemanager': 'Trình quản lý tệp',
    'app.terminal': 'Terminal',
  },
  'permission.access': {
    'mode': 'Chế độ truy cập, hiện tại: {name}',
    'close': 'Đóng',
    'preset.readOnly': 'Chỉ xem',
    'preset.workspaceWrite': 'Chỉnh sửa trong Workspace',
    'preset.fullAccess': 'Toàn quyền',
    'confirm.title': 'Xác nhận bật Toàn quyền?',
    'confirm.description': 'Sau khi bật Toàn quyền, agent sẽ giảm các bước xác nhận và có thể trực tiếp thực hiện nhiều thao tác hơn, bao gồm thao tác nhạy cảm, sửa tệp hoặc lệnh bên ngoài. Chỉ nên dùng khi bạn tin tưởng tác vụ hiện tại.',
    'confirm.acknowledge': 'Tôi hiểu rủi ro và muốn tiếp tục',
    'confirm.cancel': 'Hủy',
    'confirm.enable': 'Bật Toàn quyền',
    'auto.label': 'Auto review',
    'auto.badge': 'EXP',
    'auto.description': 'Chạy không có sandbox; mỗi lượt gọi công cụ và PTC được mô hình xem xét thử nghiệm trước.',
    'auto.confirm.title': 'Xác nhận bật Auto review (Thử nghiệm)?',
    'auto.confirm.description': 'Auto review không dùng sandbox. Mỗi lượt gọi công cụ sẽ được xem xét bởi cùng mô hình agent. Tính năng này đang thử nghiệm và sẽ tiêu tốn thêm token.',
    'auto.confirm.acknowledge': 'Tôi hiểu các rủi ro này và muốn tiếp tục',
    'auto.confirm.enable': 'Bật Auto review',
  },
  'plan': {
    'chip.label': 'Kế hoạch',
    'preview.title': 'Kế hoạch',
    'preview.document': 'Kế hoạch · Markdown',
    'preview.action': 'Mở',
    'preview.open': 'Mở kế hoạch ở thanh bên',
    'preview.full': 'Xem toàn văn',
    'preview.openNamed': 'Mở kế hoạch: {title}',
    'preview.loading': 'Đang đọc kế hoạch…',
    'preview.failed': 'Không thể đọc kế hoạch',
    'preview.invalidAddress': 'Địa chỉ kế hoạch không hợp lệ',
    'preview.historyUnavailable': 'Không thể đọc lịch sử phiên',
    'preview.notFound': 'Không tìm thấy bản kế hoạch này',
    'preview.unavailable': 'Bản xem trước kế hoạch không khả dụng',
    'preview.expired': 'Bản xem trước tạm thời đã hết hạn. Hãy mở lại từ thẻ phê duyệt đang chờ.',
    'chip.on.aria': 'Chế độ kế hoạch đang bật, bấm để tắt',
    'chip.on.title': 'Chế độ kế hoạch đang bật — nhấp để tắt (/plan off)',
    'chip.off.aria': 'Chế độ kế hoạch đang tắt, bấm để bật',
    'chip.off.title': 'Chế độ kế hoạch đang tắt — nhấp để bật (/plan)',
    'chip.exitFailed': 'Thoát chế độ kế hoạch thất bại',
  },
  'question': {
    'error.incomplete': 'Vui lòng hoàn thành câu hỏi này trước.',
    'error.unanswered': 'Vui lòng chọn một tùy chọn hoặc nhập câu trả lời tùy chỉnh.',
    'nav.prev': 'Câu trước',
    'nav.next': 'Câu sau',
    'nav.minimize': 'Thu gọn thẻ câu hỏi',
    'nav.maximize': 'Mở rộng thẻ câu hỏi',
    'nav.cancel': 'Bỏ qua nhóm câu hỏi',
    'option.recommended': 'Khuyên dùng',
    'custom.placeholder': 'Nhập câu trả lời của bạn',
    'action.skip': 'Bỏ qua',
    'action.next': 'Câu tiếp',
    'plan.header': 'Đang chờ duyệt kế hoạch',
    'plan.approve': 'Đồng ý thực hiện',
    'plan.decline': 'Từ chối',
    'plan.discuss': 'Yêu cầu chỉnh sửa',
  },
  'reference': {
    'section.files': 'Tệp & thư mục',
    'section.subagents': 'Subagent',
    'section.sessions': 'Cuộc trò chuyện',
    'candidate.noCwd': '(không có thư mục làm việc)',
    'crumb.root': 'Workspace',
    'time.now': 'vừa xong',
    'time.minutes': '{n} phút',
    'time.hours': '{n} giờ',
    'time.days': '{n} ngày',
    'time.months': '{n} tháng',
    'time.years': '{n} năm',
  },
  'schedule.catalog': {
    'trigger.one': '{count} lời nhắc',
    'trigger.other': '{count} lời nhắc',
    'list.aria': 'Lời nhắc đang hoạt động',
    'status.scheduled': 'Đang chờ',
    'status.overdue': 'Đã quá hạn',
    'frequency.once': 'Một lần',
    'frequency.every': 'Mỗi {value} {unit}',
    'unit.day.one': 'ngày',
    'unit.day.other': 'ngày',
    'unit.hour.one': 'giờ',
    'unit.hour.other': 'giờ',
    'unit.minute.one': 'phút',
    'unit.minute.other': 'phút',
    'unit.second.one': 'giây',
    'unit.second.other': 'giây',
    'relative.now': 'Đến hạn ngay bây giờ',
    'relative.future': 'trong {value} {unit}',
    'relative.overdue': 'đã quá hạn {value} {unit}',
  },
  'skill': {
    'row.title': 'Kỹ năng',
    'row.running': 'Đang tải skill',
    'row.failed': 'Tải skill thất bại',
    'row.stopped': 'Tải skill đã dừng',
    'row.instructions': 'Hướng dẫn',
    'row.inspect': 'Kiểm tra',
    'menu.userOnly': 'chỉ người dùng',
  },
  'slash.menu': {
    'command': 'Lệnh',
    'skill': 'Kỹ năng',
    'subagent': 'Subagent',
    'loading': 'Đang tải…',
    'drill.aria': 'Duyệt thư mục',
    'drill.hint': 'Duyệt thư mục',
    'drill.key': 'Tab',
    'crumbs.aria': 'Điều hướng thư mục',
    'suggestions.aria': 'Gợi ý kích hoạt',
  },
  'subagent': {
    'duration.seconds': '{seconds}s',
    'duration.minutes': '{minutes}m {seconds}s',
    'duration.hours': '{hours}h {minutes}m {seconds}s',
    'duration.days': '{days}d',
    'duration.daysHours': '{days}d {hours}h',
    'duration.months': '~{months}th',
    'duration.monthsDays': '~{months}th {days}d',
    'duration.years': '~{years}n',
    'duration.yearsMonths': '~{years}n {months}th',
    'duration.exactDays': '{days} ngày {hours} giờ {minutes} phút {seconds} giây',
    'duration.exactTitle': 'Tổng thời gian hoạt động: {duration}',
    'tokens.thousand': '{value}K',
    'tokens.million': '{value}M',
    'tokens.total': '{value} tok',
    'loading.label': 'Đang tải subagent…',
    'load.error': 'Không thể tải subagent',
    'retry': 'Thử lại',
    'mode.oneShot': 'một lần',
    'mode.continuable': 'có thể tiếp tục',
    'mode.unknown': 'chế độ không rõ',
    'readonly.unknown.body': 'Đọc phiên con để xác định có thể tiếp tục hay không.',
    'activity.running': 'đang chạy',
    'activity.completed': 'đã hoàn tất',
    'activity.inactive': 'không chạy',
    'branch.collapse': 'Thu gọn cấp dưới của {label}',
    'branch.expand': 'Mở rộng cấp dưới của {label}',
    'count.total.one': '{count} subagent',
    'count.total.other': '{count} subagent',
    'count.running.one': '{count} subagent đang chạy',
    'count.running.other': '{count} subagent đang chạy',
    'switcher.aria': 'Chuyển subagent: {title}',
    'tree.aria': 'Các phiên subagent',
    'open.sidebar': 'Mở {label} ở thanh bên',
    'sidebar.chat': 'Trò chuyện',
    'readonly.oneShot.title': 'Bản ghi subagent một lần',
    'readonly.title': 'Subagent này tạm thời chỉ đọc',
    'readonly.oneShot.body': 'Tác vụ một lần không nhận thêm tin nhắn; bạn có thể xem lại toàn bộ bản ghi tại đây.',
    'readonly.body': 'Phiên cha hiện không trực tuyến; hãy mở lại phiên cha để tiếp tục gửi tin nhắn.',
  },
  'workflowRun': {
    'run.title': '{name}',
    'run.members.one': '{count} thành viên',
    'run.members.other': '{count} thành viên',
    'run.empty': 'Không có thành viên nào được khởi chạy',
    'phase.unassigned': 'Chưa phân giai đoạn',
    'phase.empty': 'Tên giai đoạn trống',
    'statusCount.running': 'Đang chạy {count}',
    'statusCount.completed': 'Đã hoàn tất {count}',
    'statusCount.failed': 'Thất bại {count}',
    'statusCount.cancelled': 'Đã hủy {count}',
    'statusCount.interrupted': 'Đã ngắt {count}',
    'member.empty': 'Tên thành viên trống',
    'member.open': 'Mở {name}',
    'status.running': 'Đang chạy',
    'status.completed': 'Đã hoàn tất',
    'status.failed': 'Thất bại',
    'status.cancelled': 'Đã hủy',
    'status.interrupted': 'Đã ngắt',
  },
  'settings': {
    'trigger': 'Cài đặt',
    'desktop.update.available': 'Bản mới',
    'desktop.update.checking': 'Đang kiểm tra cập nhật…',
    'desktop.update.progress': '{percent}%…',
    'desktop.update.verifying': 'Đang xác thực tệp cập nhật…',
    'desktop.update.installing': 'Đang chuẩn bị khởi động lại…',
    'desktop.update.ready': 'Cài đặt và Khởi động lại',
    'desktop.update.retry': 'Thử cập nhật lại',
    'desktop.update.versionDetail': '{label} — V{version}',
    'desktop.update.downloadDetail': 'Đang tải bản cập nhật: {percent}%\nPhiên bản đích: V{version}',
    'desktop.update.checkFailed': 'Kiểm tra cập nhật thất bại, vui lòng thử lại sau.',
    'desktop.update.downloadFailed': 'Tải bản cập nhật thất bại, vui lòng thử lại.',
    'desktop.update.installFailed': 'Cài đặt cập nhật thất bại, vui lòng thử lại sau.',
    'desktop.update.checkNetworkFailed': 'Kiểm tra cập nhật thất bại do mạng gián đoạn. Vui lòng kiểm tra kết nối và thử lại.',
    'desktop.update.downloadNetworkFailed': 'Tải bản cập nhật thất bại do mạng gián đoạn. Vui lòng kiểm tra kết nối và thử lại.',
    'desktop.update.installNetworkFailed': 'Cài đặt cập nhật thất bại do mạng gián đoạn. Vui lòng kiểm tra kết nối và thử lại.',
    'desktop.update.stopFailed': 'Không thể dừng tác vụ an toàn, bản cập nhật chưa được cài. Vui lòng thử lại sau.',
    'desktop.update.tasksChanged': 'Có tác vụ mới bắt đầu, vui lòng xác nhận cập nhật lại.',
    'desktop.update.tasksUnavailable': 'Không thể xác nhận trạng thái tác vụ, hãy thử lại khi workspace đã sẵn sàng.',
    'title': 'Cài đặt',
    'close': 'Đóng',
    'openDocument': 'Mở tệp cấu hình',
    'openDocument.error': 'Không thể mở tệp cấu hình',
    'general.nav': 'Cài đặt chung',
    'general.currentVersion': 'Phiên bản hiện tại: {version}',
    'developerTools.title': 'Công cụ nhà phát triển',
    'developerTools.error': 'Lưu thất bại, vui lòng thử lại',
    'developerTools.description': 'Hiển thị các công cụ và thông tin phục vụ gỡ lỗi và chẩn đoán',
    'connection.error': 'Mất kết nối',
    'connection.connecting': 'Đang kết nối lại',
    'connection.connected': 'Đã kết nối',
    'connection.reconnect': 'Mất kết nối, nhấp để kết nối lại',
    'connection.restart': 'Đang kết nối lại, nhấp để thử ngay',
  },
  'settings.account': {
    'close': 'Đóng',
    'addApiKey': 'Thêm API Key',
    'retry': 'Đăng nhập lại',
    'loginTitle': 'Bắt đầu sáng tạo',
    'loginDescription': 'Đăng nhập để tạo, chỉnh sửa và chia sẻ các dự án của bạn. Mọi dữ liệu được lưu cục bộ.',
    'browserTitle': 'Đang chờ đăng nhập',
    'browserPrompt': 'Trình duyệt không tự mở? ',
    'copyLink': 'Sao chép liên kết đăng nhập',
    'copiedLink': 'Đã sao chép liên kết',
    'copyFailed': 'Sao chép thất bại',
    'browserDescription': ', sau đó mở trong trình duyệt để hoàn tất đăng nhập.',
    'timeoutTitle': 'Đăng nhập đã hết thời gian',
    'timeoutDescription': 'Vui lòng đăng nhập lại để tiếp tục.',
    'failureTitle': 'Đăng nhập thất bại',
    'platformFailed': 'Thao tác chưa hoàn thành, vui lòng thử lại',
    'platformRetry': 'Thử lại',
    'loading': 'Đang tải…',
    'backToHarness': 'Quay lại DeepSeek Harness',
    'settings': 'Cài đặt',
    'contactUs': 'Liên hệ chúng tôi',
    'menu': 'Menu tài khoản',
    'nav': 'Tài khoản & số dư',
    'signedIn': 'Đã đăng nhập DeepSeek',
    'signedOut': 'Chưa đăng nhập',
    'signIn': 'Đăng nhập',
    'signOut': 'Đăng xuất',
    'cancel': 'Hủy',
    'open': 'Mở trình duyệt',
    'initializing': 'Đang khởi tạo đăng nhập…',
    'waiting': 'Vui lòng tiếp tục trong trình duyệt',
    'completing': 'Đang hoàn tất đăng nhập…',
    'expired': 'Phiên đăng nhập đã hết hạn, vui lòng thử lại.',
    'failed': 'Thao tác thất bại, vui lòng thử lại.',
    'settingsSignedOutTitle': 'Hiện chưa đăng nhập tài khoản DeepSeek Harness',
    'settingsSignedOutDescription': 'Đăng nhập tài khoản DeepSeek Harness để nhận API Key chuyên dụng',
    'signInDescription': 'Đăng nhập bằng tài khoản DeepSeek để bắt đầu',
    'profileUnavailable': 'Thông tin tài khoản chưa khả dụng',
    'balance': 'Số dư nạp',
    'bonusBalance': 'Số dư khuyến mãi',
    'balanceUnavailable': 'Xem trên Nền tảng',
    'balanceSignedOut': 'Đăng nhập để xem',
    'accountInfo': 'Xem thêm thông tin tài khoản',
    'more': 'Thêm',
    'usage': 'Xem lượng sử dụng',
    'topUp': 'Nạp tiền',
  },
  'settings.agentLoop': {
    'title': 'Vòng lặp Agent',
    'description': 'Kiểm soát cách Agent điều phối và gọi công cụ.',
    'maxParallel': 'Số công cụ gọi song song',
    'maxParallelHint': 'Giới hạn tối đa số lượt gọi công cụ an toàn có thể chạy đồng thời trong một bước.',
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'invalidNumber': 'Vui lòng nhập một số, hoặc để trống để dùng giá trị mặc định.',
  },
  'settings.agentPreset': {
    'builtInGroup': 'Tích hợp sẵn',
    'customGroup': 'Tùy chỉnh',
    'sectionIntro': 'Chọn công cụ và phương thức làm việc của Agent. Dùng "Chế độ tiêu chuẩn" cho tác vụ hàng ngày, hoặc "Chế độ sáng tạo" để mở rộng năng lực DSH.',
    'seatHint': 'Chọn preset Agent cho tác vụ mới của bạn',
    'headerHint': 'Preset Agent được chọn khi tác vụ này bắt đầu',
    'nav': 'Preset Agent',
    'setDefault': 'Đặt làm mặc định cho tác vụ mới',
    'presetStandardName': 'Chế độ tiêu chuẩn',
    'presetStandardDescription': 'Làm việc với mã nguồn, tệp tin và thông tin; phù hợp cho hầu hết tác vụ với tìm kiếm, chỉnh sửa, lệnh terminal và các công cụ khác khi cần.',
    'presetPtcName': 'Chế độ PTC',
    'presetPtcDescription': 'Bao gồm toàn bộ năng lực của chế độ Tiêu chuẩn; tối ưu hơn cho tác vụ gọi công cụ hàng loạt rồi lọc, sắp xếp, loại trùng, thống kê hoặc tóm tắt kết quả.',
    'presetMinimalName': 'Chế độ tối giản',
    'presetMinimalDescription': 'Agent chỉ sử dụng công cụ terminal để hoàn thành tác vụ; phù hợp cho thử nghiệm và so sánh hiệu năng cơ bản.',
    'presetCordisName': 'Chế độ sáng tạo',
    'presetCordisDescription': 'Tùy biến DSH thông qua trò chuyện: để Agent viết plugin bổ sung tính năng hoặc giao diện; kết hợp công cụ và prompt để tạo chế độ riêng.',
    'inUse': 'Mặc định cho tác vụ mới',
    'selectionOffDefault': 'Mặc định của ứng dụng',
    'noDescription': 'Chưa có mô tả.',
    'brokenBadge': 'Tải thất bại',
    'switchRefused': 'Không thể chuyển sang "{name}": {reason}',
    'close': 'Đóng',
    'creatorDraft': 'Để Agent giúp tôi tạo một chế độ preset',
    'showPicker': 'Cho phép chọn chế độ cho tác vụ mới',
    'showPickerBeta': 'Beta',
    'showPickerDescription': 'Khi bật, mỗi tác vụ mới có thể chọn chế độ và đặt mặc định tại đây. Khi tắt, tác vụ mới dùng preset mặc định của ứng dụng.',
    'enablePickerToSetDefault': 'Bật chọn chế độ cho tác vụ mới trước khi đặt mặc định',
    'enablePickerToCreate': 'Bật chọn chế độ cho tác vụ mới trước khi khởi động Chế độ sáng tạo',
    'modeExplanation': 'Chi tiết chế độ',
    'howToUse': 'Cách sử dụng',
    'guideSections': 'Các mục hướng dẫn',
    'guideExampleTask': 'Tác vụ mẫu',
    'guideCopy': 'Sao chép',
    'guideCopied': 'Đã sao chép',
    'guideFootnotes': 'Ghi chú',
  },
  'settings.permission': {
    'title': 'Quyền hạn',
    'description': 'Chọn chế độ quyền mặc định cho các phiên mới',
    'loading': 'Đang tải',
    'unavailable': 'Không khả dụng',
    'preset.readOnly': 'Chỉ xem',
    'preset.workspaceWrite': 'Sửa trong Workspace',
    'preset.fullAccess': 'Toàn quyền',
    'confirm.title': 'Xác nhận bật Toàn quyền?',
    'confirm.description': 'Toàn quyền cho phép các phiên mới giảm bước xác nhận và trực tiếp thực thi nhiều thao tác hơn, bao gồm thao tác nhạy cảm, chỉnh sửa tệp hoặc lệnh bên ngoài. Chỉ nên bật khi bạn tin tưởng các tác vụ tiếp theo.',
    'confirm.acknowledge': 'Tôi hiểu các rủi ro và muốn tiếp tục',
    'confirm.cancel': 'Hủy',
    'confirm.enable': 'Bật Toàn quyền',
  },
  'settings.pluginInventory': {
    'tab': 'Danh sách plugin',
    'loading': 'Đang đọc plugin…',
    'clientSyncing': 'Đang đồng bộ plugin trên trang này…',
    'clientSyncFailed': 'Một số plugin không thể đồng bộ trên trang này. Trạng thái trên Host giữ nguyên.',
    'clientSyncRetry': 'Thử lại trang này',
    'error': 'Plugin tạm thời không khả dụng.',
    'metadataError': 'Lỗi siêu dữ liệu gói: {error}',
    'retry': 'Thử lại',
    'search': 'Tìm kiếm plugin',
    'empty': 'Chưa có plugin nào.',
    'emptySearch': 'Không tìm thấy plugin phù hợp.',
    'presetTitle': 'Plugin theo phiên',
    'presetSubtitle': 'Được cấu thành theo từng phiên bởi preset Agent',
    'countUnit': 'plugin',
    'switcherLabel': 'Chọn preset Agent để kiểm tra',
    'presetOptionDefault': '{name} (mặc định)',
    'presetOptionBroken': '{name} (tải thất bại)',
    'globalTitle': 'Plugin toàn cục',
    'globalSubtitle': 'Dùng chung cho toàn hệ thống và tất cả các phiên',
    'presetProvidedDetail': 'Đã tắt toàn cục; được cung cấp theo từng phiên bởi preset Agent',
    'enabledIn': 'Được bật trong',
    'viewInPreset': 'Xem trong nhóm preset',
    'matchesInOtherPresets': 'Còn {count} kết quả phù hợp trong các preset khác: ',
    'failedCountLabel': 'thất bại',
    'enabledTag': 'Đã bật',
    'disabledTag': 'Đã tắt',
    'conditionalTag': 'Có điều kiện',
    'presetEnabledTag': 'Bật qua preset',
    'failedTag': 'Khởi động thất bại',
    'moduleLabel': 'Gói / Module',
    'fromPreset': 'Từ',
    'condition': 'Tắt khi',
    'configuration': 'Cấu hình',
    'runtime': 'Trạng thái chạy',
    'unobserved': 'Chưa chạy',
    'pending': 'Đang chờ phụ thuộc',
    'loadingPhase': 'Đang nạp',
    'active': 'Đang chạy',
    'failed': 'Khởi động thất bại',
    'unloading': 'Đang gỡ bỏ',
  },
  'settings.plugins': {
    'nav': 'Plugin tích hợp',
    'title': 'Plugin tích hợp',
    'intro': 'Xem danh sách các plugin đi kèm bản triển khai này.',
    'tabs': 'Chế độ xem plugin',
    'empty': 'Bản triển khai này không hiển thị chế độ xem plugin nào.',
  },
  'settings.shell': {
    'title': 'Terminal',
    'description': 'Giới hạn thời gian chạy tối đa và dung lượng đầu ra của mỗi lệnh.',
    'timeoutMs': 'Thời gian chờ lệnh (ms)',
    'timeoutMsHint': 'Một lệnh được phép chạy trong bao lâu trước khi bị ngắt.',
    'maxOutputBytes': 'Giới hạn đầu ra mỗi luồng (bytes)',
    'maxOutputBytesHint': 'Phần vượt quá giới hạn sẽ được lưu tạm vào tệp thay vì bị loại bỏ.',
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'invalidNumber': 'Vui lòng nhập một số, hoặc để trống để dùng giá trị mặc định.',
  },
  'settings.subagent': {
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'subagentTitle': 'Subagent',
    'subagentDescription': 'Thiết lập độ sâu đệ quy, số lượng và mô hình của Subagent.',
    'subagentLimitsTitle': 'Giới hạn vận hành',
    'subagentMaxDepth': 'Độ sâu đệ quy tối đa',
    'subagentDepthHelpLabel': 'Giải thích về độ sâu đệ quy tối đa',
    'subagentDepthHelp': 'Giới hạn số tầng Subagent mà một Agent có thể tạo ra.',
    'subagentDepthZero': 'Vô hiệu hóa Subagent',
    'subagentDepthOne': 'Chỉ Agent chính mới được tạo Subagent',
    'subagentDepthOverride': 'Nếu một công cụ có thiết lập độ sâu riêng, thiết lập của công cụ đó sẽ được ưu tiên.',
    'subagentMaxActive': 'Giới hạn số Subagent chạy song song',
    'subagentCapacityHelpLabel': 'Giải thích về giới hạn Subagent song song',
    'subagentCapacityHelp': 'Tổng số Subagent hoạt động đồng thời dưới cùng một Agent chính, trên mọi tầng đệ quy (không tính Agent chính). Khi đạt giới hạn, các yêu cầu tạo mới sẽ bị từ chối.',
    'subagentDepthInvalid': 'Vui lòng nhập số nguyên từ 0 trở lên.',
    'subagentCapacityInvalid': 'Vui lòng nhập số nguyên từ 1 trở lên.',
    'subagentModelSelectionTitle': 'Lựa chọn mô hình',
    'subagentModelSelectionToggle': 'Cho phép Agent chọn mô hình cho Subagent',
    'subagentModelSelectionChoose': 'Khi bật, Agent có thể chọn nhà cung cấp, mô hình và mức suy luận cho từng Subagent từ danh sách được ủy quyền bên dưới. Chỉ áp dụng cho các phiên mới.',
    'subagentModelSelectionAllowed': 'Các mô hình Agent được phép chọn',
    'subagentModelSelectionLoading': 'Đang tải mô hình…',
    'subagentModelSelectionLoadFailed': 'Không thể tải mô hình.',
    'subagentModelSelectionRetry': 'Thử lại',
    'subagentModelSelectionPartial': 'Một số nhà cung cấp mô hình tạm thời không thể tải; các lựa chọn đã lưu vẫn có thể xóa.',
    'subagentModelSelectionUnavailable': 'Hiện không khả dụng',
    'subagentModelSelectionUnavailableGroup': 'Đã lưu nhưng hiện không khả dụng',
    'subagentModelSelectionEmpty': 'Hiện không có nhà cung cấp mô hình nào công bố mô hình.',
    'subagentModelSelectionRequired': 'Vui lòng chọn ít nhất một mô hình trước khi lưu.',
    'subagentModelSelectionConflict': 'Cài đặt đã thay đổi ở nơi khác. Hãy bỏ bản nháp và thử lại.',
    'subagentModelSelectionOff': 'Khi tắt, Subagent sẽ dùng mô hình mặc định hoặc kế thừa mô hình của Agent cha; các lựa chọn đã lưu vẫn được giữ.',
  },
  'settings.webSearch': {
    'title': 'Tìm kiếm web',
    'description': 'Cấu hình nhà cung cấp tìm kiếm DeepSeek.',
    'apiKey': 'API Key',
    'apiKeyHint': 'Lưu ngoài tệp cài đặt. Để trống để giữ khóa hiện tại.',
    'apiKeySet': 'Đã cấu hình khóa API.',
    'apiKeyUnset': 'Chưa cấu hình khóa API; tìm kiếm web không khả dụng cho đến khi được cấu hình.',
    'baseUrl': 'Địa chỉ máy chủ (Endpoint)',
    'baseUrlHint': 'Để trống để dùng địa chỉ mặc định của nhà cung cấp.',
    'maxUses': 'Số lần tìm kiếm tối đa mỗi yêu cầu',
    'maxUsesHint': 'Số lần một yêu cầu có thể tìm kiếm trước khi bắt buộc phải đưa ra câu trả lời.',
    'overridden': 'Đã ghi đè',
    'reset': 'Khôi phục mặc định',
    'readOnly': 'Bản triển khai này lưu cài đặt ở chế độ chỉ đọc.',
    'unavailable': 'Plugin này chưa được nạp nên tạm thời không thể định cấu hình.',
    'save': 'Lưu',
    'saving': 'Đang lưu…',
    'saveFailed': 'Hệ thống không chấp nhận các giá trị này; giữ nguyên để bạn sửa lại.',
    'invalidNumber': 'Vui lòng nhập một số, hoặc để trống để dùng giá trị mặc định.',
  },
  'sidebar': {
    'session.new': 'Phiên mới',
    'session.new.label': 'Tạo phiên mới',
    'toggle.open': 'Mở thanh bên',
    'toggle.collapse': 'Thu gọn thanh bên',
    'panels.label': 'Bảng điều khiển toàn cục',
  },
  'sidebarBrowser': {
    'type.label': 'Trình duyệt',
    'guide.title': 'Trình duyệt',
    'guide.description': 'Duyệt các trang web',
    'address.placeholder': 'Nhập địa chỉ HTTP(S)',
    'address.changed': 'URL đã thay đổi',
    'back': 'Quay lại',
    'forward': 'Tiến lên',
    'reload': 'Tải lại',
    'go': 'Đi đến',
    'external': 'Mở trong trình duyệt hệ thống',
    'sandbox.disable': 'Tắt giới hạn sandbox',
    'sandbox.enable': 'Khôi phục giới hạn sandbox',
    'sandbox.warning': 'Giới hạn sandbox đã tắt; trang web có thể điều hướng ứng dụng cấp cao nhất, tải tệp, hiển thị hộp thoại modal và khóa nhập liệu.',
    'start': 'Nhập địa chỉ HTTP(S) để bắt đầu duyệt',
    'loading': 'Đang mở…',
    'restore.previous': 'Đã mở lần trước',
    'restore.action': 'Khôi phục trang',
    'error.empty': 'Vui lòng nhập địa chỉ.',
    'error.invalid': 'Địa chỉ này không hợp lệ hoặc quá dài.',
    'error.protocol': 'Chỉ hỗ trợ giao thức HTTP và HTTPS; tệp cục bộ vui lòng dùng Xem trước tài liệu.',
    'error.credentials': 'Địa chỉ không được chứa tên người dùng hoặc mật khẩu.',
    'error.application-origin': 'Trình duyệt nhúng không thể mở chính ứng dụng DSH.',
    'load.failed': 'Tải trang thất bại; vui lòng làm mới hoặc mở trong trình duyệt hệ thống.',
    'load.failed.detail': 'Tải trang thất bại ({code}): {description}',
    'address.unknown': 'Trang web đã chuyển hướng; không thể đọc URL mới.',
  },
  'sidebarFiles': {
    'type.label': 'Tệp tin',
    'guide.title': 'Tệp trong Workspace',
    'guide.description': 'Duyệt các tệp trong workspace của phiên này',
    'loading': 'Đang đọc…',
    'empty': 'Thư mục trống',
    'truncated': 'Có quá nhiều mục, chỉ hiển thị một phần.',
    'noWorkspace': 'Phiên này không có thư mục workspace.',
    'reload': 'Tải lại',
    'autoRefresh': 'Tự động làm mới',
    'autoRefresh.enable': 'Bật tự động làm mới',
    'autoRefresh.disable': 'Tắt tự động làm mới',
    'entry.other': 'Đây không phải tệp hoặc thư mục hợp lệ để mở.',
    'error.notFound': 'Thư mục này không còn tồn tại. Có thể đã bị di chuyển hoặc xóa.',
    'error.outsideWorkspace': 'Thư mục này nằm ngoài workspace nên thanh bên sẽ không đọc nó.',
    'error.notDirectory': 'Đây không phải là một thư mục.',
    'error.unavailable': 'Đọc thất bại: {message}',
  },
  'sidebarRight': {
    'chrome.expand': 'Mở thanh bên',
    'chrome.expandAria': 'Mở thanh bên phải',
    'chrome.collapse': 'Thu gọn thanh bên',
    'chrome.collapseAria': 'Thu gọn thanh bên phải',
    'chrome.toFullscreen': 'Toàn màn hình',
    'chrome.exitFullscreen': 'Thoát toàn màn hình',
    'dock.emptyPane': 'Khung trống',
    'dock.splitPane': 'Chia cột',
    'dock.splitPaneDisabled': 'Đã đạt giới hạn tối đa hai cột',
    'dock.splitPaneNarrow': 'Chiều rộng không đủ để chia cột, hãy kéo rộng thanh bên',
    'dock.closeTab': 'Đóng',
    'dock.addTab': 'Thẻ mới',
    'dock.dockFloat': 'Thu về thanh bên',
    'dock.closeFloat': 'Đóng',
    'dock.drop.center': 'Di chuyển vào đây',
    'dock.drop.left': 'Thêm cột trái',
    'dock.drop.right': 'Thêm cột phải',
    'dock.drop.top': 'Thêm hàng trên',
    'dock.drop.bottom': 'Thêm hàng dưới',
    'tab.guide.title': 'Bắt đầu',
    'tab.unavailable': 'Chưa có trình xem nào hỗ trợ loại nội dung này.',
  },
  'sidebarTerminal': {
    'recoveryFailed': 'Khôi phục terminal thất bại: {message}',
    'retryRecovery': 'Thử lại khôi phục terminal',
    'shell': 'Chọn Shell',
    'shellLoading': 'Đang đọc Shell…',
    'shellEmpty': 'Không có Shell nào khả dụng',
    'description': 'Chạy lệnh trong workspace của phiên',
    'title': 'Terminal',
    'new': 'Terminal mới',
    'loading': 'Đang đọc môi trường terminal…',
    'creating': 'Đang khởi động…',
    'connecting': 'Đang kết nối…',
    'disconnected': 'Kết nối đã ngắt.',
    'reconnect': 'Kết nối lại',
    'readonly': 'Chế độ xem này hiện chỉ đọc.',
    'control': 'Tiếp quản nhập liệu',
    'closed': 'Terminal đã đóng.',
    'exited': 'Tiến trình đã thoát ({code})',
    'failed': 'Lỗi terminal: {message}',
    'rename': 'Tên terminal',
    'unavailable': 'Không khả dụng',
    'retry': 'Thử lại',
    'cleanupFailed': 'Không thể dừng terminal "{title}": {message}',
    'missingTerminal': 'Terminal này không còn tồn tại, hãy mở terminal mới.',
    'inputFull': 'Bộ đệm nhập liệu đã đầy, hãy kết nối lại rồi thử lại.',
    'attachmentEnded': 'Kết nối terminal đã kết thúc, hãy kết nối lại.',
    'invalidOutput': 'Truyền tải màn hình terminal bị lỗi, hãy kết nối lại.',
    'terminalLimit': 'Số lượng terminal đã đạt giới hạn tối đa. Vui lòng đóng bớt terminal không dùng.',
  },
  'sidebarDocumentPreview': {
    'loading': 'Đang đọc…',
    'loadMore': 'Tải thêm',
    'changed': 'Tệp đã thay đổi, đang hiển thị nội dung cũ',
    'reloadNow': 'Tải lại ngay',
    'reload': 'Đọc lại tệp',
    'autoRefresh': 'Tự động làm mới',
    'autoRefresh.enable': 'Bật tự động làm mới',
    'autoRefresh.disable': 'Tắt tự động làm mới',
    'wrap.enable': 'Bật tự động xuống dòng',
    'wrap.disable': 'Tắt tự động xuống dòng',
    'wrap.aria': 'Tự động xuống dòng',
    'openWith': 'Mở bằng',
    'viewer.text': 'Văn bản thuần',
    'resourceUnavailable': 'Dịch vụ tài nguyên tệp không khả dụng',
    'rendererUnavailable': 'Trình xem trước {name} không khả dụng',
    'unsupportedFile': 'Định dạng tệp này tạm thời chưa thể xem trước',
    'error.notFound': 'Tệp không tồn tại, có thể đã bị di chuyển hoặc xóa',
    'error.tooLarge': 'Nội dung trang vượt quá giới hạn {limit}, không thể đọc',
    'error.notText': 'Định dạng tệp này tạm thời chưa thể xem trước',
    'error.notRegularFile': 'Đường dẫn này không phải tệp thông thường, không có nội dung để hiển thị',
    'error.unavailable': 'Đọc thất bại: {message}',
    'retry': 'Thử lại',
  },
  'sidebarCodePreview': {
    'title': 'Mã nguồn',
    'copy': 'Sao chép',
    'copied': 'Đã sao chép',
  },
  'sidebarExcel': {
    'title': 'Bảng tính',
    'language': 'vi',
    'loading': 'Đang mở bảng tính…',
    'invalid': 'Không thể mở bảng tính này. Hãy kiểm tra định dạng tệp, nội dung hoặc mật khẩu bảo vệ.',
    'tooLarge': 'Bảng tính này vượt quá giới hạn kích thước xem trước.',
    'timeout': 'Mở bảng tính bị quá thời gian. Hãy thử với tệp nhỏ hơn.',
    'encoding': 'Không thể nhận dạng mã hóa văn bản. Hãy lưu tệp dưới dạng UTF-8 hoặc UTF-16 có BOM rồi thử lại.',
    'formulaWarning': 'Bảng tính này có chứa công thức, kết quả hiển thị có thể bị thiếu hoặc không chính xác.',
    'unsupportedNotice': 'Bản xem trước hiện không hỗ trợ {features} trong tệp này. Hãy mở bằng ứng dụng hệ thống để có trải nghiệm đầy đủ.',
    'charts': 'biểu đồ',
    'images': 'hình ảnh',
    'shapes': 'hình vẽ',
    'conditionalFormatting': 'định dạng có điều kiện',
    'featureSeparator': ', ',
    'retry': 'Thử lại',
  },
  'sidebarImage': {
    'zoomControls': 'Điều khiển thu phóng',
    'zoomMenu': 'Chọn tỷ lệ thu phóng',
    'zoomOut': 'Thu nhỏ',
    'zoomIn': 'Phóng to',
    'zoomFitWidth': 'Vừa chiều rộng',
    'zoomValue': '{percent}%',
    'title': 'Hình ảnh',
    'preview': 'Xem trước ảnh: {name}',
    'loading': 'Đang đọc…',
    'failed': 'Không thể hiển thị hình ảnh này',
    'unsupported': 'Xem trước ảnh cần toàn bộ nội dung tệp',
  },
  'sidebarOffice': {
    'title': 'Tài liệu Office',
    'loading': 'Đang đọc…',
    'retry': 'Thử lại',
    'viewMissingFonts': 'Thiếu {count} phông chữ, nhấp để xem',
    'missingFontsTitle': 'Phông chữ bị thiếu',
    'missingFontsDescription': 'Bản xem trước không có các phông chữ này; văn bản và bố cục có thể khác với tài liệu gốc.',
    'missingFontsCount': '{count} phông chữ',
    'closeDetails': 'Đóng chi tiết phông chữ',
    'unavailable': 'Xem trước Office không khả dụng. Hãy bật dịch vụ xem trước tài liệu trên máy chủ chạy DeepSeek Harness.',
    'invalid': 'Không thể xem trước tệp Office này. Tệp có thể bị hỏng, có mật khẩu hoặc sai phần mở rộng.',
    'tooLarge': 'Tệp Office hoặc PDF sau chuyển đổi vượt quá dung lượng tối đa. Hãy giảm kích thước tệp hoặc chỉnh cấu hình xem trước.',
    'failed': 'Chuyển đổi Office thất bại, không tạo được PDF khả dụng. Vui lòng kiểm tra lại tệp.',
    'timeout': 'Chuyển đổi Office bị quá thời gian, vui lòng thử lại.',
    'busy': 'Dịch vụ xem trước Office đang bận, vui lòng thử lại sau ít phút.',
    'changed': 'Tệp đã thay đổi trong khi đang đọc. Vui lòng mở lại bản xem trước.',
  },
  'sidebarPdf': {
    'zoomControls': 'Điều khiển thu phóng',
    'zoomMenu': 'Chọn tỷ lệ thu phóng',
    'zoomOut': 'Thu nhỏ',
    'zoomIn': 'Phóng to',
    'zoomFitWidth': 'Vừa chiều rộng',
    'zoomValue': '{percent}%',
    'title': 'PDF',
    'pageImage': 'Trang PDF {page}',
    'loading': 'Đang đọc…',
    'rendering': 'Đang hiển thị trang…',
    'failed': 'Không thể hiển thị PDF: {message}',
    'password': 'Tệp PDF này có mật khẩu bảo vệ, hiện chưa hỗ trợ xem trước',
    'workerFailed': 'Tiến trình hiển thị PDF gặp sự cố, vui lòng thử lại',
    'unsupported': 'Xem trước PDF cần toàn bộ nội dung tệp',
    'retry': 'Thử lại',
  },
  'directory-browser': {
    'browser.title': 'Chọn thư mục Workspace',
    'browser.home': 'Thư mục chính',
    'browser.newFolder': 'Thư mục mới',
    'browser.folderName': 'Tên thư mục',
    'browser.createIn': 'Tạo thư mục mới trong "{name}"',
    'browser.untitledFolder': 'Thư mục chưa đặt tên',
    'browser.create': 'Tạo',
    'browser.cancel': 'Hủy',
    'browser.open': 'Mở',
    'browser.editPath': 'Sửa đường dẫn',
    'browser.loading': 'Đang tải…',
    'browser.truncated': 'Quá nhiều thư mục để hiển thị, chỉ hiển thị phần đầu.',
    'browser.showHidden': 'Hiển thị tệp ẩn',
  },
  'documentHtml': {
    'title': 'HTML',
    'frame': 'Xem trước tài liệu HTML',
    'loading': 'Đang đọc…',
    'failed': 'Không thể xem trước tài liệu HTML này.',
  },
  'documentMarkdown': {
    'viewer.label': 'Markdown',
    'code.copy': 'Sao chép',
    'code.copied': 'Đã sao chép',
    'footnotes': 'Chú thích',
  }
};

const allDicts = {
  ...core,
  ...convDicts,
  ...panelDicts,
  ...additionalDicts,
};

console.log(`Assembled ${Object.keys(allDicts).length} namespaces.`);

// Write features.ts and surfaces.ts back to harness for completeness
const featuresNames = [
  'approval', 'command', 'deliverables', 'feedback', 'goal', 'job', 'model',
  'open-in-app', 'permission.access', 'plan', 'question', 'reference',
  'schedule.catalog', 'skill', 'slash.menu', 'subagent', 'workflowRun'
];
const surfacesNames = [
  'settings', 'settings.account', 'settings.agentLoop', 'settings.agentPreset',
  'settings.permission', 'settings.pluginInventory', 'settings.plugins',
  'settings.shell', 'settings.subagent', 'settings.webSearch',
  'sidebar', 'sidebarBrowser', 'sidebarFiles', 'sidebarRight', 'sidebarTerminal',
  'sidebarDocumentPreview', 'sidebarCodePreview', 'sidebarExcel', 'sidebarImage',
  'sidebarOffice', 'sidebarPdf', 'directory-browser', 'documentHtml', 'documentMarkdown'
];

const featuresObj = {};
for (const n of featuresNames) {
  if (additionalDicts[n]) featuresObj[n] = additionalDicts[n];
}
const surfacesObj = {};
for (const n of surfacesNames) {
  if (additionalDicts[n]) surfacesObj[n] = additionalDicts[n];
}

fs.writeFileSync(
  'D:\\Project\\deepseek-harness\\packages\\client\\locale\\src\\locales\\vi\\features.ts',
  `/** Vietnamese shard: feature namespaces. */\nexport const dicts = ${JSON.stringify(featuresObj, null, 2)} satisfies Record<string, Record<string, string>>\n`
);

fs.writeFileSync(
  'D:\\Project\\deepseek-harness\\packages\\client\\locale\\src\\locales\\vi\\surfaces.ts',
  `/** Vietnamese shard: surfaces and settings namespaces. */\nexport const dicts = ${JSON.stringify(surfacesObj, null, 2)} satisfies Record<string, Record<string, string>>\n`
);

// Now generate the standalone plugin bundle: lib/client.js
const clientBundle = `/* global window, localStorage */
// lib/client.js — Vietnamese language pack for DeepSeek Harness Web UI
window.__ModuleLoader__.load({
  id: "dsh-vietnamese-lang",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;

    const name = "dsh-vietnamese-lang";
    const inject = ["locale"];

    const DICTS = ${JSON.stringify(allDicts, null, 2)};

    function apply(ctx) {
      const locale = ctx.get("locale");
      if (!locale || typeof locale.register !== "function") {
        console.warn("[dsh-vietnamese-lang] locale service unavailable");
        return;
      }

      // 1. Add Vietnamese language definition if addLanguage is supported
      if (typeof locale.addLanguage === "function") {
        try {
          ctx.effect(
            () => locale.addLanguage({ id: "vi", label: "Tiếng Việt", fallback: "en" }),
            "dsh-vietnamese-lang: language definition"
          );
        } catch (e) {
          // ignore if already added
        }
      }

      // 2. Register all Vietnamese dictionaries
      for (const [ns, dict] of Object.entries(DICTS)) {
        try {
          ctx.effect(
            () => locale.register(ns, "vi", dict),
            "dsh-vietnamese-lang: " + ns
          );
        } catch (error) {
          console.error("[dsh-vietnamese-lang] Failed to register " + ns, error);
        }
      }

      // 3. Fallback / patch snapshot if addLanguage is not natively in locale
      if (typeof locale.getLocale === "function") {
        const snap = locale.getLocale();
        const locales = snap.locales || snap.options || [];
        if (!locales.some((l) => l.id === "vi")) {
          const next = [...locales, { id: "vi", label: "Tiếng Việt" }];
          try {
            locale.snapshot = Object.freeze({
              ...snap,
              locales: Object.freeze(next),
              options: Object.freeze(next),
            });
            if (typeof locale.publish === "function") {
              locale.publish(snap.active, true);
            }
          } catch (_) {}
        }
      }

      // 4. Persistence with localStorage for smooth experience
      const STORAGE_KEY = "dsh-vietnamese-lang.preference";
      const readPref = () => {
        try { return localStorage.getItem(STORAGE_KEY); } catch (_) { return null; }
      };
      const writePref = (val) => {
        try {
          if (val) localStorage.setItem(STORAGE_KEY, val);
          else localStorage.removeItem(STORAGE_KEY);
        } catch (_) {}
      };

      if (typeof locale.setLocale === "function") {
        const origSet = locale.setLocale.bind(locale);
        locale.setLocale = (id) => {
          if (id === "vi") {
            writePref("vi");
            if (typeof locale.publish === "function") locale.publish("vi", true);
            else origSet("vi");
          } else {
            writePref(null);
            origSet(id);
          }
        };
      }

      const activateIfPreferred = () => {
        if (readPref() === "vi" && locale.getLocale().active !== "vi") {
          try {
            if (typeof locale.publish === "function") locale.publish("vi", true);
            else if (typeof locale.setLocale === "function") locale.setLocale("vi");
          } catch (_) {}
        }
      };

      if (typeof locale.adopt === "function") {
        const origAdopt = locale.adopt.bind(locale);
        locale.adopt = (host) => {
          origAdopt(host);
          activateIfPreferred();
        };
      }
      activateIfPreferred();
    }

    exports.name = name;
    exports.inject = inject;
    exports.apply = apply;
    return module.exports;
  }
});
`;

fs.writeFileSync('D:\\Project\\dsh-vietnamese-lang\\lib\\client.js', clientBundle);
console.log('Successfully wrote D:\\Project\\dsh-vietnamese-lang\\lib\\client.js');
